spack/spack-infrastructure

gitlab-docker/README.md, gitlab-docker/docker-compose.yml, gitlab-docker/vars.sh
This is an attempt to have a way to test the cloud deployment pipeline in the local, `docker-compose` service environment provided by this repo.
=> Add a storage service compatible with S3

gitlab-docker/TRIGGERS.md
Document how triggers can be set up allowing the use of API requests to trigger pipelines.
=> WIP: Document triggers example

kubernetes/spack/cdash-spack-io/db/deployments.yaml, kubernetes/spack/gitlab-spack-io/cache/deployments.yaml, kubernetes/spack/gitlab-spack-io/db/deployments.yaml, kubernetes/spack/gitlab-spack-io/web/deployment.yaml, kubernetes/spack/staging-spack-io/cdash/db/deployments.yaml
Changes the deployment strategies of several services from the default "rollout" to "replace".
Necessary for deployments with `replicas=1` and who mount persistent volumes.  With `replace` strategy, the pod running the service is completely removed before being recreated.  This strategy avoids issues where the "replacement" pod in a rollout cannot successfully start because they need resources held by the original pod.
Note that to achieve higher availability and/or zero downtime deployments require that a service be redefined in terms of replicasets and dynamic volumes.  This change only affects services that either cannot be deployed using a rolling strategy (e.g.: databases, because they do not support it) or for which we haven't gone through the trouble of redeploying them in a …
=> update deployment strategies of several services to "replace"

kubernetes/cluster/ingress-nginx/controller/configmaps.yaml, kubernetes/cluster/ingress-nginx/controller/deployments.yaml, kubernetes/spack/gitlab-spack-io/db/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/medium/deployments.yaml, kubernetes/spack/gitlab-spack-io/web/config-maps.yaml, kubernetes/spack/gitlab-spack-io/web/deployment.yaml, kubernetes/spack/gitlab-spack-io/web/pv.yaml, kubernetes/spack/gitlab-spack-io/web/pvc.yaml
- Increase worker timeout for NGINX ingress to 15
minutes.
- Increase number of replicas running NGINX
ingress to 3.
- Bump version of NGINX controller up to 0.21.0.
- Increase shared buffer size for POSTGRES DB to
256 MB.
- Increase max connections for POSTGRES DB to
1000.
- Increase log level of "medium" Gitlab CI
runners to "debug".
- Add a watchdog script that runs alongside
Gitlab and prints a log line when the memory
or storage utilization rises above 90%.
- Fix a long-standing issue where Gitlab used the
wrong external_url in its generated links and
messages.
- Migrated Gitlab service from running on a
dedicated m4.large instance to a dedicated
r5.xlarge instance.
- Increase the storage for Gitlab from 20 GB to
100 GB.
=> add several reliability improvements for Gitlab

kubernetes/spack/gitlab-spack-io/web/deployment.yaml
For posterity's sake, let it be known that this upgrade from 12.8 to 12.9 required us to run the following command from the gitlab container:
`gitlab-rake db:migrate`
=> Bump the gitlab version for update-permissions

kubernetes/spack/gitlab-spack-io/runner/config-maps.yaml, kubernetes/spack/gitlab-spack-io/runner/large/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/medium/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/t3.micro/deployments.yaml, kubernetes/spack/gitlab-spack-io/web/deployment.yaml
- Configures Gitlab service to ensure the presence of the `gitlab-*` elasticsearch indexes.
- Removes the debugging arguments in our medium runner.
- Increases large runners to three (3) replicas.
- Adds a new set of t3.micro runners, currently set to five (5) replicas.  These new runners include an experimental elasticsearch integration implementation.
The details of the ES implementation are in the new `gitlab-runner-scripts` ConfigMap.  Additional mounts can't be specified for pods created by the Kubernetes executor, so the implementation works around this limitation by generating pre-build and post-build scripts, which are passed along to runners verbatim when registering.  Unfortunately, this additional level of indirection can make the script logic very tough to follow.  The general …
=> Better elastic search integration

README.md
The release number in the README had not been updated since we did the
relicense to Apache-2.0 OR MIT in v0.12.0. LLNL-CODE-811652 is Spack's
new LLNL release number.
=> README: Update LLNL release number to Apache-2.0/MIT version

kubernetes/cluster/autoscaler/deployments.yaml, kubernetes/cluster/ingress-nginx/controller/deployments.yaml, kubernetes/cluster/ingress-nginx/default-http-backend/deployments.yaml, kubernetes/cluster/kubernetes-dashboard/heapster/deployments.yaml, kubernetes/cluster/kubernetes-dashboard/influxdb/deployments.yaml, kubernetes/cluster/kubernetes-dashboard/web/deployments.yaml, kubernetes/spack/gitlab-spack-io/cache/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/large/deployments.yaml, kubernetes/spack/gitlab-spack-io/web/deployment.yaml
Also adds the following changes:
- Upgrades cluster autoscaler from v1.12.3 to v1.14.7
- Changes the instance type for the instance running Gitlab from `r5.xlarge` to `r5.4xlarge`.
=> update specs for kubernetes 1.15

kubernetes/spack/gitlab-spack-io/runner/c5n.2xlarge/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/c5n.xlarge/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/large/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/medium/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/r5.2xlarge/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/t2.large/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/t3.micro/deployments.yaml, kubernetes/spack/gitlab-spack-io/runner/t3.nano/deployments.yaml, kubernetes/spack/kibana-spack-io/daemonset.yaml, kubernetes/spack/misc/auto-updater/cron-jobs.yaml
Use images pushed to GitHub container registry personal account to temporarily work around recent dockerhub pull rate limits.
Supersedes #48
=> Temporarily mitigate docker apocalypse using ghcr

gh-gl-sync/SpackCIBridge.py, gh-gl-sync/requirements.txt, gh-gl-sync/test_SpackCIBridge.py, kubernetes/spack/internal-spack-io/gh-gl-sync/cron-jobs.yaml
Changed all four github api requests to use PyGithub, as it provides a much simpler way to handle pagination (compared to doing it ourselves by reading the "Link" headers from the response).
It seems gitlab also paginates its api results, see [here](https://docs.gitlab.com/12.10/ee/api/README.html#pagination).  However, since we only query for pipelines associated with a single branch at a time, and since we further restrict the time range to the last few minutes, I didn't make any effort to handle pagination for the gitlab api requests.  It looks like the default is for gitlab to return 20 items per page, which seems like it might be fine for our purposes here.
=> Handle result pagination

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py
This is designed to fix the problem we discovered today where by the time the E4S pipeline runs, we might merge a much more recent `github/develop` into the PR branch than existed when the branch was committed/pushed to the spack github repo.  If we go with this, we will then drop [this part](https://gitlab.spack.io/spack/e4s/-/blob/master/.gitlab-ci.yml#L16) of our custom `before_script`.
GitHub generates a "test commit" by merging the head of the PR branch into the base (at some point).  If that commit comes back "None" in the api query for open pulls, it is likely because it cannot be merged with the base any longer, so we skip it.
Testing against a local standin for the target gitlab remote, I can look at the branches this is now pushing and see the kind of commit message GitHub is …
=> Mirror <merge_commit_sha> rather than "refs/pulls/<pr_number>/head"

k8s/gitlab/temporary/release.yaml
Looking at the StorageClass associated with the persistent volume claims in the new cluster, it seems we may have dynamic volume provisioning as described [here](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/).  So this change may be enough to cause Kubernetes to create another volume of 100GB on behalf of gitlabs minio.
Not sure how to apply this change, given that it's in a helm chart and supposed to be managed by flux.
=> Increase minio pvc size llnl

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py
When we changed the sync script to test the merge_commit_sha created
by github, we failed to recognize that the commit used for posting
status back to github was just whatever was found in the gitlab
pipeline api endpoint.  Posting status back to the merge commit does
not make any sense and does not result in the status being visible
on the PRs.
This change fetches the tested commit from each pipeline, and then
parses the PR sha out of the result, and we use that sha to post
status to github.
=> Post status to the correct commit on github

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py
Some status post started failing because we posted more than 1K status on a single commit.  I think there some old PRs not moving forward and we do not first check github to see if we have already posted status for a commit (we don't want to do that, unless we don't care about testing new `merge-commit-sha` for PRs when `develop` moves forward).
In this case, it's this [PR](https://github.com/spack/spack/pull/20802), where we detected it could not be merged (github had no `merge-commit-sha` for it), and we have now posted that fact as a status more times than github allows on a single commit.
Thankfully we do the unmergeables after the other statuses, so this didn't actually stop us from posting on active PRs.
=> Make sure we continue posting status even if one fails

kubernetes/spack/slack-spack-io/web/certificates.yaml, kubernetes/spack/slack-spack-io/web/deployments.yaml, kubernetes/spack/slack-spack-io/web/ingress.yaml, kubernetes/spack/slack-spack-io/web/services.yaml
This is a draft deployment attempting to move the [slackin](https://github.com/emedvedev/slackin-extended) app hosted at https://spackpm.herokuapp.com to https://slack.spack.io.
=> Add slack.spack.io to spack-infrastructure

k8s/gitlab/release.yaml, k8s/gitlab/sidekiq.dockerfile, k8s/gitlab/task-runner.dockerfile, k8s/gitlab/webservice.dockerfile
Even though it appears we should no longer need this, we are hitting
yaml size limits when pipeline generation creates a yaml file of
around 400 KB on disk.  This change replaces the patching of docker
images we previously used to get around the yaml size limitations,
while keeping us on the latest patch release of gitlab.
=> Fix yaml size limits issue

k8s/runners/large-pub/release.yaml, k8s/runners/medium-pub/release.yaml, k8s/runners/small-pub/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-pub/release.yaml, scripts/eks-node-group.yaml
In addition to the CloudFormation stack we created earlier today, this should give us one of the pools of graviton2 runners we need.  I `kubectl apply -f`'d  the release file so I could test it out, seems to be working.  See the pipeline here: 
https://gitlab.spack.io/scott/test-downstream/-/pipelines/43281
That's a private repo, but I added the reviewers as members, except Omar who doesn't seem to have an account on that instance.
=> Add HelmRelease for one new pool of graviton runners (c6g.4xlarge)

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
The goal of this PR is to reduce a lot of wasted compute time by
avoiding pushing branches where the base sha is the currently running
develop pipeline sha.  Once the develop pipeline has completed, those
branches will be pushed the next time the sync script runs.
=> Reduce number of redundant spec builds after a PR is merged

k8s/gitlab/release.yaml
It's my hunch that this is the cause of the recent errors we've been
seeing in GitLab CI pipelines:
```
WARNING: Uploading artifacts as "archive" to coordinator...
failed  id=451296 responseStatus=500 Internal Server Error status=500
```
After shelling into our minio pod and running `df` I saw the following
suspicious output:
```
/dev/nvme1n1             98.3G     97.2G      1.0G  99% /export
```
=> Bump storage for GitLab MinIO

k8s/ingress-nginx/release.yaml
This should resolve the HTTP 413 errors we've seen when attempting to upload
large XML files to cdash.spack.io
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-body-size
=> Increase client_max_body_size for nginx-ingress

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
We noticed some pipelines slipping through the cracks & not
getting their statuses posted back to GitHub.
Also improve log messages related to a branch's base commit.
=> Bump 'brief threshold' from 4 to 15 minutes

k8s/spack/spackbot-spack-io/deployments.yaml, k8s/spack/spackbot-spack-io/secrets-dummy.yaml
This adds one secret to the `spackbot` environment so that it can restart pipelines on gitlab.spack.io.
This also adds a `secrets-dummy.yaml` file so that I can remember how the heck to format private keys so that Kubernetes will actually give them to the bot correctly.  You can look in the file to see commands that will work.
=> spackbot: deploy new version; Add GITLAB_TOKEN to secrets

k8s/spack/spackbot-spack-io/deployments.yaml, k8s/spack/spackbot-spack-io/secrets-dummy.yaml
This is the prod deploy of #111.
=> spackbot: Add GITLAB_TOKEN to spackbot in production

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
I continue to notice the occasional pipeline not getting its updated status posted back to GitHub.
=> Bump 'brief threshold' from 15 to 30 minutes

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
It's still a mystery why this is happening, but we continue to see the
occasional GitHub PR not get its status updated after the corresponding
GitLab CI pipeline has finished running.
=> Increase brief threshold again

gh-gl-sync/SpackCIBridge.py
I think this should fix an issue the sync script had preventing it from seeing pipelines on certain branches.
=> URL encode branch names before hitting gitlab pipeline api

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Instead of marking a PR backlogged anytime the github merge  commit includes a running develop, only backlog PRs if we would otherwise have needed to push its branch too.
=> Only backlog PRs we would otherwise have pushed

k8s/cdash/deployments.yaml
This should fix a bug we noticed where some API endpoints
attempt to get loaded over http instead of https.
=> Set $CDASH_PRODUCTION_MODE = 1

k8s-bootstrap/flux-chart.yaml, k8s/gitops/deployments.yaml, k8s/gitops/namespace.yaml, k8s/gitops/pvc.yaml, k8s/gitops/secrets.yaml
Adds my custom gitops controller.
Container image taken from my Github registry.  See https://github.com/opadron/images/tree/main/gitops for code and details.
TODO:
- This should get flux to switch from observing the `production` branch to the `flux` branch
=> Gitops migration

.github/workflows/custom_docker_builds.yml, images/gitops/entrypoint.py, k8s/gitlab/staging/certificates.yaml, k8s/gitlab/staging/release.yaml, k8s/gitops/deployments.yaml, k8s/runners/staging/release.yaml, scripts/gitops-patch.py
Adds canary deployments for Gitlab and one gitlab runner.  The runner is configured to run up to 3 jobs at a time on the `base` node pool.  The jobs can share instance resources with each other as well as any other pods running on the pool.  This should be fine for testing, and has the added benefit that jobs should start up and run quickly since it is unlikely that they would need to wait for cluster autoscaler to bring up a new instance.
While producing these patches, the value of having a tool to preview the results of applying a patch to some resources became clear, and so I also added the `gitops-patch.py` script.  This script can apply a patch and show you the result.  It uses the same logic that my `gitops` controller uses when applying patches.
As a final detail, I had to manually …
=> Gitlab canary

.github/workflows/custom_docker_builds.yml, images/gitops/entrypoint.py, k8s/gitlab/staging/certificates.yaml, k8s/gitlab/staging/release.yaml, k8s/gitops/deployments.yaml, k8s/runners/staging/release.yaml
Fixes two other issues identified during maintenance:
1. Fixes an issue where the gitops controller wasn't initializing properly on its first iteration.
2. Adds the new patch config maps to their correct namespaces.
=> fix gitops initialization logic/add gitlab namespace to patches

k8s/runners/staging/release.yaml
There's a setting in the gitlab runner helm chart called `pollTimeout`.  This value controls how long a job will idle waiting for its pod to come up before giving up and failing the job.  I had overridden this value in the staging runner because I thought it was for something else.
This was a mistake that causes the runner's jobs to fail when spinning up a new instance through cluster autoscaler.  I set the value to 30 seconds, which is not enough time.
Here, I undo that mistake, leaving the setting to its original value of ten minutes.
=> remove poll timeout override

k8s/gitlab/staging/release.yaml
Looks like I forgot to remove a temporary change in the staging Gitlab patch file.  This change removed some fields in the helm release related to the images.  The effect of this was to revert those fields back to their default values.  I probably added this before I had the custom images ready, and then forgot to remove it.
=> switch staging gitlab back to our custom images

k8s/cdash/deployments.yaml
This should allow us to more easily cope with 'bursty' workflows.
=> turn on async parsing for CDash

k8s/runners/huge-x86-pub/release.yaml
I don't completely understand why, but the amount of memory we were
requesting (94Gi) was too much for cluster-autoscaler to spin up a new instance
for huge jobs:
```
Pod <snip> can't be scheduled on <huge-ASG>, predicate checking error:
Insufficient memory; predicateName=NodeResourcesFit;
reasons: Insufficient memory; debugInfo=
```
I also tried 90 GiB, but this resulted in the same error. Thus, the current
value of 88 GiB was more-or-less discovered by trial & error.
=> Allow huge jobs to run on the glr-huge-pub pool

k8s/prometheus/release.yaml
By default we lose prometheus info on pod crash. This should prevent that from happening.
=> Add PVC to prometheus stateful Set

scripts/error-classification.py
```
Usage: error-classification.py [OPTIONS] COMMAND [ARGS]...
Classification tools for Spack Errors
Provides tools to get job log traces and classify them based on a taxonomy
of errors. Logs are grepped for strings and matching error class columns are
set to true in a resulting CSV. multiple classes may match a job log and so
errors may be 'deconflicted' based on a pirorty list.
Error CSVs must be in the proper format. These can be exported from the
following Metabase Analytic:
https://metabase.spack.io/question/16-job-errors-api-ink
Example Usage:
$> error-classification.py -l INFO get-logs -t [GITLAB_API_TOKEN] 20211227-7days.csv
$> error-classification.py -l INFO classify 20211227-7days.csv
$> error-classification.py stats 20211227-7days_annotated.csv
...
Options:
-l, --log-level …
```
=> Add script that does job error classification

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
We were inadvertently posting a status message of:
"Pending -- base"
...when we really meant to be saying:
"Pending -- waiting for base develop commit pipeline to succeed"
This bug fix will also cause us to link to the currently running develop pipeline from the pending status that gets posted to GitHub.
=> Fix status posted for PRs backlogged by a running develop pipeline

k8s/runners/huge-x86-pub/release.yaml
I don't completely understand why, but the amount of memory we were
requesting (94Gi) was too much for cluster-autoscaler to spin up a new instance
for huge jobs:
Pod <snip> can't be scheduled on <huge-ASG>, predicate checking error:
Insufficient memory; predicateName=NodeResourcesFit;
reasons: Insufficient memory; debugInfo=
I also tried 90 GiB, but this resulted in the same error. Thus, the current
value of 88 GiB was more-or-less discovered by trial & error.
=> Allow huge jobs to run on the glr-huge-pub pool (merge to production)

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
Readjusts all the worker memory requests based on 88 Gi of allocatable memory on the `c5.12xlarge` nodes.
=> Gitlab runner resource limits tweak (push to production)

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
After #163, we're getting hit by a nasty Gitlab Runner bug where stale pods are being left around after they have finished building their packages.  As far as we can tell, these pods are left running indefinitely, occupying resources and preventing new work from running.  We don't know why this issue is affecting us, nor why it only started after we changed the way our runners were deployed.  This is a critical issue affecting the pipelines, and our immediate response is to revert the changes in the hopes that it goes away.
After this is merged, I'll update the underlying `huge` pools to only run up to 20 instances.
=> Gitlab runner revamp revert (push to production)

k8s/runners/large-x86-tmp-pub/release.yaml
Temporarily adds a new `large` runner that will run side-by-side with the current runners.  This temporary runner will accept new jobs with the `large` tag and pack them into `c5.12xlarge` instances.  These instances are provisioned using a temporary node pool, `glr-huge-tmp-pub`.  The runner is currently set to run up to 10 jobs at a time.
The plan is to introduce this new runner and monitor jobs for evidence of the "stuck" pods issue we were observing last week.  Assuming the runner runs without issues, we will gradually increase the capacity until we observe the "stuck" pods issue, again.
=> add temporary large runner (push to production)

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
cherry-pick the changes from #172 and #174 into production
We were inadvertently posting a status message of:
"Pending -- base"
...when we really meant to be saying:
"Pending -- waiting for base develop commit pipeline to succeed"
This bug fix will also cause us to link to the currently running develop
pipeline from the pending status that gets posted to GitHub.
=> Fix status posted for backlogged PRs (merge to production)

.github/workflows/custom_docker_builds.yml, k8s/gitlab/staging/release.yaml
Background: Our `gitlab` and `gitlab-staging` helm releases are currently stuck in `failed` states.  This can happen for a variety of reasons.  The releases need to be returned to a healthy state in order for flux to continue managing them automatically.  This operation requires manual intervention.
This PR tries to address one of the reasons for the failure (there may be others): Gitlab had switched their component naming around so that what they used to call "gitlab-task-runner" is now "gitlab-toolbox".  This change is reflected in the `values.yaml` of their helm charts, so we need to manually update our helm releases.
This PR also updates the custom image that we use for running `gitlab-task-runner`.
=> transition away from gitlab-task-runner to gitlab-toolbox

k8s/ingress-nginx/release.yaml
Increases max replicas by 4x, since the HPA has been oversubscribed by more than 3x.  This should leave a comfortable-enough margin for the replica count.
=> increase nginx max replicas

k8s/gitlab/release.yaml, k8s/gitlab/staging/release.yaml
- Set minio volume to 1Ti, which is what it actually is in the cluster.
- Increase postgresql volume size from 8Gi -> 100Gi.
=> fix issues with Gitlab data persistence (push to production)

k8s/prometheus/release.yaml
Note this required significant manual intervention on cluster related to
Custom Resource Definitions
=> Bump kube-prometheus-stack from 19.2.2 to 32.0.2

k8s/prometheus/alertmanagerconfig.yaml, k8s/prometheus/customalerts.yaml, k8s/prometheus/customrules.yaml, k8s/prometheus/release.yaml, scripts/dummyalert.sh
This makes sure all alert messages are picked up by the `AlertmanagerConfig` custom resource in the `monitoring` namespace.  Note that alerts originated in `source_namespace`
Note that It may be possible to do some post-alert label processing to rewrite source_namespace back to namespace. If so i would do that as a follow on PR.
=> Prometheus alertmanager hack

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/large-x86-tmp-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/staging/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
Pick a new Helm chart version (0.37.2) which, according to
https://artifacthub.io/packages/helm/gitlab/gitlab-runner/,
is the most recent version of the chart which provides 14.7.0.
=> Runners: Switch from bleedingedge to 14.7.0

k8s/cdash/cron-jobs.yaml, k8s/custom/gh-gl-sync/cron-jobs.yaml, k8s/custom/gitlab-api-scrape/cron-jobs.yaml, k8s/custom/rotate-keys/cron-jobs.yaml, k8s/spack/packages-spack-io/cron-jobs.yaml, k8s/spack/www-spack-io/cron-jobs.yaml
1. Pull the `ci-key-clear` image from ghcr.io (not Docker Hub)
2. Update gh-gl-sync to not recreate failed pods
3. Move out of the beta apiVersion for batch
=> Updates and fixes to our CronJobs

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/large-x86-tmp-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/staging/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
Eliminate the usage of several deprecated Helm variables in the
release.yaml file by setting the config.toml to contain those values
directly.
Deprecated options are marked here:
https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml
Commit SHA: 477f145bedcb68690d723826831d9c8c4f5b2d09
=> Send deprecated entries via config.

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/large-x86-tmp-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/staging/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
Adds annotations and labels to pods running the pipeline namespace. These are mostly pulled from the Job variables,  but include a few `SPACK_*` specific variables for propagation down into the metrics labels which will be a follow on PR
=> Add Labels and Annotations to Job Pods

k8s/spack/spackbot-spack-io/deployments.yaml
This PR adds a worker pod to the spackbot deployment which will handle
asynchronously the work of fixing isort style for PRs.  The worker pod
can be used for other asynchronous tasks in the future as well (e.g. PR
binary graduation), and we can increase the number of replicas if
necessary to handle the extra load.
=> Support spackbot fixing style in worker process

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Up until now, we've been unconditionally posting status to commits on GitHub. If we post too many statuses to a single commit then GitHub will not allow us to update it later. This causes a PR to be blocked until we manually intervene.
Other things this PR does:
* Print messages about our rate limit usage
* Cache calls to the ["get a commit" GitHub API endpoint](https://docs.github.com/en/rest/reference/commits#get-a-commit) in an effort to preserve our rate limit
* Suppress irrelevant errors emanating from `git log`
* Don't use GitLab CI to test draft PRs
* Reduce our cron job frequency from 3 minutes to 4 minutes in another attempt to preserve our rate limit
=> (SpackCIBridge) Stop posting duplicate statuses to commits

k8s/prometheus/release.yaml
This will help us make dashboards that track specific performance of the pipeline namespace,  pods, nodes, etc
@opadron PTAL - if this is ok,  can we get it in before the next maintenance window?  I am blocked moving forward on pipeline dashboards until then.  
Thanks!
=> Add useful labels to metrics for nodes

scripts/count-nodes.sh
Adds a small utility script that we can run to get a breakdown of how many nodes of each availability zone - node pool combination are registered.
```
./count-nodes.sh
2 us-east-1a base
1 us-east-1a beefy
1 us-east-1a gitlab
3 us-east-1b base
2 us-east-1b gitlab
3 us-east-1c base
1 us-east-1c gitlab
3 us-east-1d base
2 us-east-1d gitlab
1 us-east-1d glr-glr-testing
```
=> add count-nodes script

k8s/prometheus/ingress.yaml, k8s/prometheus/release.yaml, k8s/prometheus/secrets.yaml
This allows authentication with https://grafana.spack.io/  via GitHub OAuth provided you're a member of the `spack` organization.
=> Config Grafana for Github Oauth

k8s/aws-node-termination-handler/release.yaml, k8s/helm-operator/release.yaml
Daemonset that will monitor for termination events (such as in the case of Spot interruption) and gracefully drain a node before the instance is terminated.
=> Add AWS node termination handler

k8s/runners/large-x86-pub/release.yaml, k8s/runners/large-x86-testing-pub/release.yaml, k8s/runners/staging/release.yaml
Also fixes a minor oversight returning our staging runner to one replica.
=> Hotfix: fix runner tags

.github/workflows/custom_docker_builds.yml, images/gitlab-clear-pipelines/Dockerfile, images/gitlab-clear-pipelines/README.md, images/gitlab-clear-pipelines/cancel_and_restart_stuck_pipelines.py, images/gitlab-clear-pipelines/requirements.txt, k8s/custom/unstick-pipelines/cron-jobs.yaml, k8s/custom/unstick-pipelines/secrets-dummy.yml
Query gitlab for running pipelines that were created more than
a day ago and try to run a new pipeline on the ref associated
with each stuck pipeline.  Also query for the pipelines child
pipelines, and try to cancel each one before finally canceling
the parent.
=> Look for stuck pipelines and run a new pipeline on the branch

k8s/runners/large-x86-pub/release.yaml, k8s/runners/large-x86-testing-pub/release.yaml
The x86 runners run on `m5zn.3xlarge` instances which have a memory
limit of 48GB, match the runners maximum to that.
The same change needs to occur for CPU, as the instance has 12 CPU
available, not 16.
=> Drop the maximum values to match runner's specs

k8s/runners/large-x86-pub/release.yaml
I think it's true that if a processor supports `avx512`, then it supports all of these.  Correct me if I'm wrong though.
=> Add level tags to the large x86_64 runner

.github/workflows/custom_docker_builds.yml, images/python-aws-bash/Dockerfile
This image can be used at the end of each pipeline to copy the
binary packages up to the mirror root (or wherever), and at the
end of all pipelines to rebuild the spack binary index.
=> Create an image for the merging of per-stack mirrors

scripts/update-public-key.sh
Just a quick script to upload the "Spack Project Official Binaries" public key to locations in the mirrors required for verification.  Useful for if new releases are cut that require the key,  or if new signatures/etc are added and need to be re-published.
=> Add script to update public key in mirrors

k8s/runners/large-x86-prot/release.yaml
Need these for the aws stacks coming through soon.
=> runners: add level tags to protected x86 runners

k8s/gitlab/release.yaml, k8s/gitlab/staging/release.yaml, scripts/migrate-pvc.py
Updates the postgresql subchart to run with 4 read replicas.  The hope is that these additional replicas will spread the IOPS load across multiple volumes, improving site reliability during peaks in demand.
In addition: a new `storageclass` based on `gp3` EBS volumes is planned.  The read replicas will be using this new storageclass, and the existing postgresql data storage will also be migrated to this new storageclass.
The details of getting this data migration right are very nuanced and addressing these details by hand is likely to be a very error-prone process, so this PR also includes a script that I wrote to automate this process.
When this PR is ready, and at a time of our choosing, we will need to take a planned outage and follow the checklist below to perform the necessary …
=> Prepare data migration

k8s/gitlab/staging/release.yaml, scripts/migrate-pvc.py
Updates the staging gitlab release to explicitly reference the new `gp3-small` storage class (suitable for PVCs with size >= 1Gi and size <= 32Gi).
Also, fixes an issue with the `migrate-pvc.py` script where some of its query operations did not pass the right kubernetes namespace to `kubectl`.
=> update staging gitlab release / fix migrate-pvc.py script (Push to Production)

k8s/spack/spackbotdev-spack-io/README.md
Update documentation to reflect reality as learned recently while
practicing the development workflow for spackbot.  Adding annotations
on the pods themselves doesn't prevent flux from noticing your test
changes to the deployments and "fixing" them for you.  Instead,
the annotation telling flux to ignore changes needs to be applied
to the deployments.
=> Fix spackbotdev workflow documentation

k8s/gitlab/release.yaml, k8s/gitlab/secrets.yaml, k8s/gitlab/staging/release.yaml
Gitlab's guide to using an external DB: https://docs.gitlab.com/charts/advanced/external-db/
First, we'll test out the RDS migration in staging. Note, because we likely do not want to maintain/pay for an additional postgres RDS instance for staging, an additional PR will be merged after this one that re-enables the in-cluster postgres DB for staging.
Steps:
```sh
kubectl exec -it gitlab-staging-postgresql-master-0 -n gitlab -- bash -c "PGPASSWORD=<db_password> pg_dump -U gitlab -d gitlabhq_production" > dump.sql
```
- Standard create
- PostgreSQL (select latest version)
- Master username: "gitlab"
- Additional configuration: 
- Initial database name: `gitlabhq_production`
`CREATE ROLE postgres;`
`CREATE ROLE gitlab;`
```sh
psql --host=<db url> --port=5432 --username=gitlab --password …
```
=> Gitlab PostgreSQL RDS migration

k8s/gitlab/release.yaml, k8s/gitlab/staging/release.yaml
The gitlab `HelmRelease` doesn't support specifying the `host` of the postgres database as a secret (ref: https://docs.gitlab.com/charts/charts/globals.html#configure-postgresql-settings), so [`valuesFrom`](https://fluxcd.io/docs/components/helm/helmreleases/#values-overrides) must be used to do this. I believe this is why staging doesn't work after #280 was merged.
=> Correctly specify hostname secret for RDS DB

.github/workflows/custom_docker_builds.yml
I noticed the `custom_docker_builds` workflow has a lot of repeated commands. A [build matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) can be used here to shorten the workflow file and eliminate the repetition.
=> Use a build matrix for building/pushing docker images

k8s/gitlab/release.yaml, k8s/gitlab/staging/release.yaml
The database instance isn't publicly accessible, so this should be safe to do.
=> Specify RDS DB hostname directly

k8s/logging/fluent-bit.yaml
Enabling the `Replace_Dots` setting in fluent-bit as suggested here https://github.com/fluent/fluent-bit/issues/4386 is apparently needed to avoid some log parsing issues. After deploying that change to the cluster and deleting the existing OpenSearch index, everything appears to be working now.
The `Trace_Error` setting enables more verbose logging for the fluent-bit pods themselves, and is what helped me debug this particular issue, so I think it's worth keeping that on as well.
=> Fix fluent-bit parsing

k8s/gitlab/secrets.yaml, k8s/logging/fluent-bit.yaml
When #291 was merged, flux overwrote all of the fluent-bit/gitlab secrets with the dummy ones in that file because the flux ignore annotation wasn't present.
=> Make flux ignore gitlab/fluent-bit secrets

k8s/gitlab/staging/release.yaml
Reverts the staging environment to use an in-cluster postgresql DB for gitlab again.
=> Use in-cluster postgres DB for staging deployment of gitlab

k8s/gitlab/staging/release.yaml
I missed this one flag, which is why #281 didn't cause a postgres pod to get deployed in the cluster :sweat_smile: 
I also changed the `op` to `replace`, which is what it should be, since the `spec/values/postgresql` field already exists in the production `release.yaml`.
=> Set `install: true` for gitlab postgres in staging

k8s/aws-node-termination-handler/release.yaml, k8s/cdash/deployments.yaml, k8s/cert-manager/release.yaml, k8s/cluster-autoscaler/release.yaml, k8s/custom/gh-gl-sync/cron-jobs.yaml, k8s/custom/gitlab-stuckpods/deployment.yaml, k8s/custom/node-share-controller/deployment.yaml, k8s/gitlab/release.yaml, k8s/gitlab/staging/release.yaml, k8s/gitops/deployments.yaml, k8s/logging/fluent-bit.yaml, k8s/metabase/metabase-deployment.yaml, k8s/prometheus/release.yaml, k8s/spack/slack-spack-io/deployments.yaml, k8s/spack/spackbot-spack-io/deployments.yaml, k8s/spack/spackbotdev-spack-io/deployments.yaml
Most of the things we deployed in the cluster do not specify the
amount of memory or cpu they request, although this information is
critical to allow kubernetes to make good pod scheduling decisions.  
This PR applies cpu and memory requests to some of the largest 
resource consumers that did not previously specify resource requests.
Using prometheus queries crafted by @kotfic, we were able to get
some measurements of what kind of resources are getting consumed
by the cluster services/apps now, and use that information to provide
these initial resource requests.  
We will need to follow up a few more PRs doing the same until we
have set requests for everything running in the cluster.
I'm not sure about the `k8s-bootstrap` changes, as to whether they'll
get picked up by flux automatically. …
=> Start specifying resource requests

k8s/spack/spackbot-spack-io/deployments.yaml
Autoscaler is having trouble scheduling this pod because of memory
issues.  The t3.small have 2G ram, so you would think we could safely
request 1.3G.  And in fact, it did get scheduled and run for a little
while with the request set to 1.3G, but was still found pending an
hour later.
=> Reduce spackbot-workers memory request

k8s/spack/spackbot-spack-io/deployments.yaml, k8s/spack/spackbotdev-spack-io/deployments.yaml
Spackbot now supports specifying the queue name as an environment
variable.  Supply different task queue names to develop vs prod
spack deployments to prevent workers from picking up jobs aimed
at the other deployment.
=> Use different queue names for develop vs production

k8s/metabase/gitlab_ro_user_job.yaml, k8s/metabase/secrets.yaml
Metabase was still pointing at the old gitlab postgres DB. This PR will point it at the RDS instance. I've already add the new secrets to the cluster.
=> Reconfigure metabase to connect to gitlab RDS postgres instance

k8s/logging/configmaps.yaml
I'm seeing errors like this showing up in the ELK dashboard for several fluent-bit pods:
`[2022/08/17 18:01:02] [ warn] [http_client] cannot increase buffer: current=32000 requested=64768 max=32000`
According to [this fluent-bit issue](https://github.com/fluent/fluent-bit/issues/3918#issuecomment-1118528986), if you have a large kubernetes cluster, the cluster metadata that fluent-bit needs to read can take up more than the default buffer size of 32KB. I've applied the suggested fix from that issue here and bumped the buffer size to 512KB.
=> Increase fluent-bit k8s buffer size

k8s/logging/secrets.yaml
Currently, our log rotation policy is "delete every OpenSearch index older than 14 days". This approach is flawed because we currently send all log records to the same index. So right now, we are essentially deleting every log in the system every 14 days.
This PR adds `Logstash_Format` and `Logstash_Prefix` settings to fluent-bit config file. These options make it so fluent-bit sends its logs to an OpenSearch index called "fluent-bit-YYYY-MM-DD"; this guarantees that a new index is created everyday, thus allowing our log rotation policy to actually work as intended.
I've applied this to the cluster already, this is just a PR to encode this into the "fake secret" in the repo.
=> Enable logstash format for OpenSearch indices

k8s/custom/gh-gl-sync/cron-jobs.yaml
It turns out the name of the check we want to gate on is "prechecks / style", not "ci / prechecks / style". If I understand correctly, "ci" is the name of the check suite.
=> Fix command line argument to SpackCIBridge.py

k8s/prometheus/alertmanagerconfig.yaml, k8s/prometheus/custom/alerts.yaml, k8s/prometheus/custom/rules.yaml, k8s/prometheus/release.yaml
This PR removes the default rules associated with kube-prometheus-stack.  While some of these rules are undoubtedly useful, many are unactionable causing the #monitoring-alerts  channel to become spammed in a way that has lead to alerting fatigue. Currently there are 3 alerting rules defined:
1. GitlabPipelineStuckPods - pods that have seen no CPU/RAM/Network activity for more than 5 minutes.
2. GitlabWebServiceErrorRate5Percent - a warning that the gitlab web services has been experiencing 5% error rates for at least 5 minutes.
3. GitlabWebServiceErrorRate10Percent - a critical warning that the gitlab web service has been experiencing 10% error rates for at least 2 minutes. 
More may be defined as actionable problems arise.
=> Remove alerting rules

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
This fixes a bug where GitHub branches named 'gitlab/...' break the sync script.
=> Only strip the first occurrence of 'gitlab/' in get_synced_prs()

.github/workflows/custom_docker_builds.yml, images/opensearch-index-build-logs/Dockerfile, images/opensearch-index-build-logs/build_logs_to_opensearch.py, images/opensearch-index-build-logs/requirements.txt, k8s/custom/opensearch-index-build-logs/cron-jobs.yaml, k8s/custom/opensearch-index-build-logs/secrets-dummy.yaml
@scottwittenburg as we discussed, I've written a Python script that iterates through the build cache, downloads any tarballs uploaded in the last day, and extracts and posts their build logs to opensearch. I've set up a cron job to run the script once a day on the cluster.
=> Cron job for posting build logs to opensearch

.github/workflows/custom_docker_builds.yml
@zackgalbreath do you see any downsides to doing this? Merging straight to production is a common pattern, but currently any changes to docker images won't be reflected until the changes are backported to main.
=> Also publish custom docker images on push to `production`

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Remove the 'waiting for base develop commit pipeline to succeed' functionality from our sync script. It doesn't jive well with '@spackbot run pipeline' and it will soon be unnecessary once we roll out PR binary graduation.
=> Stop blocking PRs due to a currently running "main branch" pipeline

k8s/karpenter/provisioners.yaml
This should help with our ARM instance capacity issues. @zackgalbreath I chose to simply remove the the restriction, without adding any additional restrictions, for the following reasons:
* GPU instances will not be provisioned if a GPU is not requested
* Based on some [old documentation](https://karpenter.sh/v0.13.1/provisioner/#instance-types) (not sure why it's no longer mentioned anywhere), karpenter will not provision metal instances unless specified in the provisioner.
From the docs:
> The default value includes all instance types with the exclusion of metal (non-virtualized), [non-HVM](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/virtualization_types.html), and GPU instances.
I think it might be easiest to just remove our restrictions, watch what instance types are being …
=> Remove instance type restriction in karpenter

k8s/karpenter/provisioners.yaml
Since we are now allowing almost all instance types to be provisioned with Karpenter, it's possible that a large node is provisioned for some temporary workload, and then is left running at a very low utilization, since pods are being scheduled onto it within the 10 minute TTL.
This PR changes our de-provisioning method to [Consolidation](https://karpenter.sh/v0.18.1/tasks/deprovisioning/#consolidation), which will optimize for cost by deprovisioning larger than necessary nodes.
=> Karpenter: Use consolidation instead of ttlSecondsAfterEmpty

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/Dockerfile, k8s/custom/gh-gl-sync/cron-jobs.yaml
The sync script image became broken recently when it was rebuilt and picked up python 3.11.  At that point, one of the dependencies of the `github` package, `wrapt`, started failing.  See here:
https://github.com/GrahamDumpleton/wrapt/issues/196
This pins `python` at 3.10 until the `github` package can update its (possibly transitive) dependency on `wrapt` to the fixed version.
=> gh-gl-sync: Fix broken sync script

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/entrypoint.sh, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml, k8s/spack/spackbot-spack-io/deployments.yaml, k8s/spack/spackbot-spack-io/service-accounts.yaml, k8s/spack/spackbotdev-spack-io/README.md, k8s/spack/spackbotdev-spack-io/deployments.yaml, k8s/spack/spackbotdev-spack-io/service-accounts.yaml
=> Add worker deployments for spackbotdev

k8s/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml
It seems the math for each runner provisioner's memory limits was low by a factor of 2. This PR essentially doubles the memory limits for each runner provisioner (except testing, which was correct).
This has has an actual impact on the `x86-64_v4` provisioner, as that's been hitting memory limits due to this, but the other provisioners haven't gotten at all close to their limits. Nonetheless, I felt it was correct to bump them to what was intended. I wouldn't be opposed to decreasing them, but that wasn't the intent of this PR.
=> Fix memory limits for runner provisioners

k8s/cluster-autoscaler/release.yaml, k8s/karpenter/provisioners/base/provisioner.yaml
This adds the karpenter provisioner required for the `base` node pool.
It doesn't seem there's any code here for the autoscaling group associated with the base node pool, so I guess that will just need to be manually deprovisioned?
=> Add provisioner for base node pool

.github/workflows/custom_docker_builds.yml, README.md, docs/deferred_pipelines.md, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Don't push PR branches to GitLab for pipeline testing if they are based on a commit of the main branch that is newer than what has already been tested by GitLab.
=> Defer GitLab pipelines based on main branch history

k8s/spack/spackbot-spack-io/deployments.yaml
Some jobs for PR graduation were not completing due to timeout
=> Extend the timeout for queued jobs

k8s/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml, k8s/runners/signing/release.yaml
* Allow Karpenter to spin up bigger instances
* c7g.8xlarge is apparently not big enough to build ParaView
* Update node pool for signing runner
* glr-large-pub doesn't exist anymore
=> Karpenter provisioner fixes

k8s/custom/gh-gl-sync/cron-jobs.yaml
This prevents more than one copy of the sync script from running at the same time.
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
=> Add `concurrencyPolicy: Forbid` to sync script cron job

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
We saw recently that fetching from the repo (via `git fetch <remote> refs/pull/<pr_number>/head:<tmp_branch>`) can produce a different pr head sha than the GH api (via `pull.head.sha`).  When that happened, we used the value from the api to make the merge commit message, but the commit contained an older PR HEAD as one of its parents.
This change checks to make sure the two values match.  If they do not match, since we cannot be sure which sha is correct, we avoid making and pushing the merge commit for the PR.
See this Spack PR [comment](https://github.com/spack/spack/pull/34452#issuecomment-1349527215) for an example and description of the problem fixed here.
=> gh-gl-sync: Make sure merge commit message matches commit parents

k8s/runners/protected/graviton/2/release.yaml, k8s/runners/protected/graviton/3/release.yaml, k8s/runners/protected/x86_64/v2/release.yaml, k8s/runners/protected/x86_64/v3/release.yaml, k8s/runners/protected/x86_64/v4/release.yaml, k8s/runners/public/graviton/2/release.yaml, k8s/runners/public/graviton/3/release.yaml, k8s/runners/public/x86_64/v2/release.yaml, k8s/runners/public/x86_64/v3/release.yaml, k8s/runners/public/x86_64/v4/release.yaml
These were originally set up for our m5zn.3xlarges. Now that we are using Karpenter, hardcoding this limit to 12 vCPUS no longer makes sense.
=> Remove CPU limits from pipeline pods

k8s/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/karpenter/provisioners/runners/testing/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml
This adds the `spack.io/pipeline: true` label to all pipeline provisioners. This was something that was missed during the karpenter switchover.
=> Add pipline label to all runner provisioners

k8s/karpenter/service-monitor.yaml
This allows for prometheus to access the exposed karpenter metrics
This has been running on the cluster for over a month, and is just the code change.
=> Add karpenter service monitor

LICENSE-MIT
=> license: fix GitHub detection of MIT license

k8s/custom/gh-gl-sync/secrets-dummy.yaml, k8s/custom/gitlab-api-scrape/secrets-dummy.yaml, k8s/custom/rotate-keys/secrets-dummy.yaml, k8s/gitlab/release.yaml, k8s/gitlab/secrets.yaml
While setting the cluster back up, I came across some secrets that were referenced in various services that didn't have a corresponding "dummy" file in the spack-infrastructure repo.
=> Add missing dummy secrets

.github/workflows/custom_docker_builds.yml, images/opensearch-index-build-logs/Dockerfile, images/opensearch-index-build-logs/build_logs_to_opensearch.py, k8s/custom/opensearch-index-build-logs/cron-jobs.yaml, k8s/custom/opensearch-index-build-logs/secrets-dummy.yaml
- Fixed regex bug where certain spackball filenames wouldn't get parsed correctly,
leading to an incorrect s3 prefix being queried for
- Check if a spackball already exists in opensearch *before* downloading
and extracting it
- Include metadata from the gitlab job that built each spackball
This has been running in the cluster for a while now and seems to work as expected.
=> Improved opensearch pipeline logs upload script

k8s/prometheus/custom/alerts.yaml
This alert is needed for our "stuck pod" mitigation in images/gitlab-stuckpods/ to function properly.
=> Reenable GitlabPipelinePodStuck alert

terraform/karpenter.tf
This changes were discovered by trial & error while attempting to get karpenter to provision nodes with attached EBS volumes
=> Update karpenter's AWSNodeTemplate

k8s/karpenter/provisioners/beefy/provisioner.yaml, k8s/karpenter/provisioners/gitlab/provisioner.yaml
I already applied these during the migration so that we could avoid having to bring in cluster-autoscaler for the new cluster. 
I basically just looked at the Auto-Scaling groups in AWS to figure out what kind of instance types cluster-autoscaler was using for these node pools; I'm not sure if this is an ideal set up, or if we want to add more instance types for these provisioners, etc. but I'll leave that to @AlmightyYakob.
=> Add Karpenter provisioners for gitlab and beefy node pools

k8s/metabase/metabase-deployment.yaml
While investigating why metabase was broken, I noticed it would occasionally get scheduled onto ARM nodes and fail with an `exec` error because the Deployment doesn't specify a node selector.
=> Specify `base` node pool for metabase

terraform/gitlab_db.tf, terraform/providers.tf
- Updates the way Terraform authenticates with the cluster to dynamically fetch a kube token instead of relying on the one that was generated when the cluster was created (that one is now expired, so `terraform apply` will not work currently without these changes)
- Makes gitlab/cdash DB terraform modules have consistent naming
- Turn on delete protection for gitlab DB
=> Misc terraform fixes

images/opensearch-index-build-logs/requirements.txt
I noticed the gitlab logs => opensearch script was failing due to this package missing. Not sure how this job was running successfully before...
=> Add missing dependency to image

images/opensearch-index-build-logs/requirements.txt
I made a typo in #379, the package is `python-gitlab`, not `gitlab` :roll_eyes:
=> Fix python-gitlab dependency name

k8s/gitlab/release.yaml
It seems that the password for the SMTP credentials used by GitLab and Metabase that's currently stored as a secret in the cluster is not correct. So, I regenerated the iam access key, which also resulted in the user name getting changed; this PR updates the GitLab helm release with this new user name.
=> Update SMTP username

.github/workflows/custom_docker_builds.yml, images/secrets-backup/Dockerfile, images/secrets-backup/backup.py, images/secrets-backup/requirements.txt, k8s/secrets-backup/cron-jobs.yaml, k8s/secrets-backup/service-accounts.yaml, scripts/restore-secret.py, terraform/modules/spack/eks.tf
This will ensure that if a secret is deleted by accident in the cluster, it isn't gone forever. A restoration script is also included.
Some things I'm still unsure about:
1. What else is needed for the image registration, or will the CI publish the docker image all on its own?
2. Is 10 minutes a good interval?
3. Should the backup/restore process include all secret metadata, labels, etc.? Currently it doesn't, but it'd be easy to include that.
I've built the container locally and run both the backup and restore scripts successfully, although I can't fully simulate the behavior in the cluster.
=> CronJob to Backup Cluster Secrets

k8s/secrets-backup/cron-jobs.yaml
Flux failed to apply the changes from #390 due to a minor syntax error - `spec.containers` is a `list`, not a `map`.
=> Fix syntax error

k8s/secrets-backup/service-accounts.yaml
Since the secrets backup cron job attempts to list secrets across _all_ namespaces, the service account it uses requires a binding to a cluster role.
=> Replace Role with ClusterRole for secrets backup script

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml, k8s/prometheus/release.yaml, k8s/prometheus/secrets-dummy.yaml
Encodes the opensearch plugin into our Grafana `HelmRelease` and points it at our opensearch instance. This will ensure we don't lose it again if the cluster goes down.
=> Configure opensearch grafana plugin

terraform/modules/spack/eks.tf
See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_addon#example-usage
Since I was specifying the addon version incorrectly, the Terraform EKS module was defaulting to the latest.
=> Fix incorrect argument name in EKS TF module

terraform/modules/spack/eks.tf
I had copy/pasted the necessary string for the OIDC `sub` field in the secrets backup iam role, but never changed it to match the namespace and service account for the secrets-backup cron job.
=> Fix incorrect OIDC sub field in secrets-backup iam role

terraform/production/main.tf
Changes the Flux configuration for the production cluster to point at spack/spack-infrastructure instead of mvandenburgh/spack-infrastructure.
=> Switch Flux to use this repo instead of fork

images/upload-gitlab-failure-logs/taxonomy.yaml
Catch errors in job traces that look like:
```
==> Error: sha256 checksum failed for /tmp/root/spack-stage/spack-stage-6chx1po1/linux-amzn2-aarch64-gcc-7.3.1-hdf5-1.14.0-46e6jm4jqbvmhr4vclfziiu7fbfamdp7.spack
```
Found, for example, [here](https://gitlab.spack.io/spack/spack/-/jobs/6081120).
=> Add regex to catch checksum mismatches

.github/workflows/custom_docker_builds.yml
Fixes some minor inconveniences/issues that I happened to notice in our docker build workflow.
- Removes the publishing of new images on push to the `production` branch. We don't use `production` for change control anymore so it is no longer "special" and shouldn't trigger new image builds.
- Removes some redundant entries in the `matrix` object - all of the removed items are duplicated in the `include` object.
- Limits the docker publish workflow to only run when an image is actually changed. We're currently wasting cycles rebuilding and uploading every docker image, even if none of them change.
=> Improvements to docker publish workflow

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
~~Depends on #411~~
Adds a pie chart to easily visualize taxonomy percentages
=> Add pie chart to error taxonomy dashboard

images/upload-gitlab-failure-logs/taxonomy.yaml
I noticed that python's `re.compile` method doesn't escape parentheses, so they're being treated as special characters instead of literals currently.
=> Escape parentheses in taxonomy regexes

images/upload-gitlab-failure-logs/taxonomy.yaml, images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py
Another kind of error being labeled as `other` are jobs with no trace, like this one https://gitlab.spack.io/spack/spack/-/jobs/6258279.
=> Add classification for failed jobs with no trace

images/upload-gitlab-failure-logs/taxonomy.yaml, images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py
All of the `no_trace` errors from the last couple weeks have a `build_failure_reason` of either `stuck_or_timeout_failure` or `scheduler_failure`. So, I think it makes more sense to fall back to those as the `error_taxonomy` if we come across jobs that failed in one of those ways.
Example of scheduler failure: https://gitlab.spack.io/spack/spack/-/jobs/6206168
Example of stuck/timeout failure: https://gitlab.spack.io/spack/spack/-/jobs/6258279
=> Remove `no_trace` error, catch timeouts and scheduler failures

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
This panel erroneously had a max value of 500, so we're better off not displaying any data for this field rather than displaying incorrect data.
This seems to be documented behavior, but I couldn't find a straightforward way of modifying it.
https://docs.aws.amazon.com/grafana/latest/userguide/using-opensearch-in-AMG.html
=> Remove "Failed Jobs" panel from GitLab CI Failures dashboard

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
I was previously ordering by "Term Value", which I thought would be the document count, but now I have no idea what it means, since it was giving the wrong results.
=> [Failed Jobs Dashboard] Order by Doc Count instead of Term Value in Pie Chart

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
The pie charts on the Error Taxonomy dashboard were essentially showing the same information as the bar charts next to them.
This commit removes these pie charts and replaces them with two new panels:
* Status of Completed Jobs: a pie chart showing success vs. failed percentages.
* Number of Completed Jobs: a self-explanatory top-level statistic.
=> Replace redundant pie charts with summary panels

images/gitlab-error-processor/job-template.yaml
Currently I don't think there's any way to filter `gitlab-error-processing-job` in the kube-events OpenSearch index. This PR adds a `label` to those Jobs so that this is possible.
=> Add label to gitlab error processing Jobs

k8s/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/karpenter/provisioners/runners/testing/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml
Consolidation doesn't really make sense for runner nodes, since all runner pods are marked as `do-not-evict` and as such, consolidation will at best just not work, and at worst cause higher costs / scheduling issues.
=> Use emptiness deprovisioning method for runner nodes

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
This will make it easier to view exactly what errors are occuring per category, from the grafana dashboard.
=> Add data links that point to opensearch

terraform/modules/spack/opensearch.tf, terraform/modules/spack/route53.tf
Adds Terraform code for provisioning a custom domain for opensearch (`opensearch.spack.io`). I already applied it to AWS, and everything appears to be working.
As part of this PR, I took a quick first pass at encoding OpenSearch into our terraform code. For now I have just encoded the OpenSearch cluster itself, and not any of the related resources like Cognito or Cloudwatch. I think in the future we'll want to have a separate Terraform module for configuring opensearch since there's so many moving parts, but until someone has the bandwidth to do that, I think this is sufficient.
=> Add custom domain for opensearch

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
For some reason, grafana was re-deployed, and since the postgres data source isn't encoded into the helm release for grafana (yet), it was erased. Since all references to data sources in grafanas use the datasource ID, this updates all mentions of the postgres data source to the new ID.
=> Update UUID of postgres data source in grafana

k8s/karpenter/provisioners/beefy/provisioner.yaml, k8s/karpenter/provisioners/gitlab/provisioner.yaml
I noticed that our `beefy` and `gitlab` node pools are currently not configured with any deprovisioning, meaning nodes that are provisioned for these node pools will stay there indefinitely, whether they're being used or not. This may not be a huge problem, but imo every provisioner should be configured with a deprovisioner of some sort, as otherwise large bursts of activity can leave empty nodes that rack up costs.
I defaulted to consolidation with these, but I'm not really sure if that fits the use case for these node pools. @zackgalbreath what do you think?
=> Add deprovisioning for beefy and gitlab provisioners

k8s/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/karpenter/provisioners/runners/testing/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml
As we discussed last week, this PR disables the usage of on-demand instances for runners. Once this is merged, we will examine 1) how this impacts the error rate of jobs (using the taxonomy dashboard), and 2) how this impacts our AWS costs (using AWS Cost Explorer).
=> Use spot instances exclusively for runners

images/gitlab-error-processor/job-template.yaml, images/upload-gitlab-failure-logs/requirements.txt, images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py
This PR ended up far from where it started, and it's goal now is to prevent duplicate build failures in opensearch. It also reorganizes the `upload_gitlab_failure_logs.py` file a bit.
=> Mark retried jobs in opensearch failure log script

k8s/prometheus/custom/pipeline-user-impact-dashboard.yaml
This encodes the Pipeline User Impact dashboard into our grafana deployment, so it doesn't get wiped out again.
=> Add back Pipeline User Impact dashboard

images/upload-gitlab-failure-logs/taxonomy.yaml
Recently we've been seeing the following errors:
```
sha256sum: command not found
```
which are being incorrectly classified as `file_not_found`, since this errors seems to directly cause that to occur afterwards.
This will require running reclassifying the last few days of errors if we'd like them to be accurate.
=> Add classification for missing sha256sum command

k8s/runners/protected/graviton/2/release.yaml, k8s/runners/protected/graviton/3/release.yaml, k8s/runners/protected/x86_64/v2/release.yaml, k8s/runners/protected/x86_64/v3/release.yaml, k8s/runners/protected/x86_64/v4/release.yaml, k8s/runners/public/graviton/2/release.yaml, k8s/runners/public/graviton/3/release.yaml, k8s/runners/public/x86_64/v2/release.yaml, k8s/runners/public/x86_64/v3/release.yaml, k8s/runners/public/x86_64/v4/release.yaml, k8s/runners/signing/release.yaml, k8s/runners/testing/graviton/2/release.yaml, k8s/runners/testing/x86_64/v3/release.yaml
This PR is aimed at placing pods on nodes that already have pods running ("pod packing"), in order to prevent low node utilization.
=> Add runner pod affinity

k8s/prometheus/custom/pipeline-user-impact-dashboard.yaml
I'll no doubt be making more changes to this, but just want to encode what I have to start.
=> Add pie chart for highest build time by package

terraform/modules/spack/outputs.tf, terraform/production/.terraform.lock.hcl, terraform/production/main.tf
The `kubectl`, `kubernetes` and `helm` providers would all raise `Unauthorized` when trying to run terraform apply/plan, even though `kubectl` functioned from the CLI without issue. This is because the role arn is provided in the local kube config file, but it was missing here.
=> Provide role arn in provider eks get-token args

k8s/prometheus/custom/gitlab-pipeline-dashboard.yaml
This new dashboards shows just two trend lines, one is pods summed for all PRs, the other is pods for develop.
=> Sum up pod counts for all PRs and show with develop pod counts

k8s/runners/public/graviton/2/release.yaml, k8s/runners/public/x86_64/v2/release.yaml
Having this tag on these runners, which should include some of the cheaper and more available instances we provision, will allow us to target these instances for the likes of the noop, cleanup, and reindex jobs.
=> Add a "service" tag to x86_64_v2 runners

images/upload-gitlab-failure-logs/taxonomy.yaml
Add more regexes to existing error categories, based on recent failures categorized as `other`.  This adds three new kinds of `network_error`, and a new kind of `concretization_error`.  Examples linked below:
- `network_error`:
- https://gitlab.spack.io/spack/spack/-/jobs/6550068
- https://gitlab.spack.io/spack/spack/-/jobs/6545225
- https://gitlab.spack.io/spack/spack/-/jobs/6543161
- `concretization_error`: https://gitlab.spack.io/spack/spack/-/jobs/6549992
=> error taxononmy: more flavors of existing classes

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
Add a panel showing all job failures (rebuild jobs, pipeline generation jobs, service jobs), broken down by whether they affected a PR or a protected pipeline (note, protected includes `develop` as well as release branches and tags).  Here's what it looks like in context:
=> Add dashboard panel showing pr vs protected failures

terraform/modules/spack/opensearch.tf, terraform/modules/spack/route53.tf, terraform/modules/spack/variables.tf, terraform/production/main.tf, terraform/staging/main.tf
The introduction of opensearch into terraform in #434 has broken our staging terraform setup, since we don't have an opensearch cluster provisioned for that. This went unnoticed because no one was actually using the staging cluster until now. This PR does a couple things to address this:
1) Makes deployment-specific aspects of opensearch (such as URL, cluster name, and cognito auth config) reliant on the deployment environment
2) Introduces a new input variable to our `spack` module, `provision_opensearch_cluster`, which allows disabling opensearch altogether.
Running this in production is currently a noop (aside from some tf state changes due to some resources being moved), so this shouldn't have any noticeable impact there.
=> Update opensearch TF to fix staging deployment

k8s/prometheus/custom/gitlab-pipeline-dashboard.yaml
Here's how it would look. This removes the "CPU Total" and "RAM Total", as there's not really room otherwise. IMO those two don't really provide much valuable info, but if other disagree, I can find some other place to put the table.
The table defaults to sorting by CPU ascending, so you can immediately see idling nodes and how many pipeline pods are on them.
=> [Pipeline Overview Dashboard] Add table showing cpu and pods per node

images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py
Adds pod "status" metadata for the k8s pod that the failed job is running on. This will allows us to identify jobs that failed due to their pod and/or one of their containers being OOMKilled, etc. 
Here's an example "status" object from a runner pod:
```
{
"conditions": [
{
"last_probe_time": null,
"last_transition_time": "2023-04-13 18:57:07+00:00",
"message": null,
"reason": null,
"status": "True",
"type": "Initialized"
},
{
"last_probe_time": null,
"last_transition_time": "2023-04-13 18:57:08+00:00",
"message": null,
"reason": null,
"status": "True",
"type": "Ready"
},
{
"last_probe_time": null,
"last_transition_time": "2023-04-13 18:57:08+00:00",
"message": null,
"reason": null,
"status": "True",
"type": "ContainersReady"
},
{
"last_probe_time": null,
"last_transition_time": …
```
=> Add info about k8s pod to gitlab job failure record

images/upload-gitlab-failure-logs/requirements.txt
I introduced the `kubernetes` python library in #427, but neglected to add it as a dependency.
=> Add missing dependency to gitlab error upload script

k8s/production/cdash/upgrade-db-schema.yaml, k8s/production/metabase/gitlab_ro_user_job.yaml, k8s/production/spack/spackbotdev-spack-io/README.md
I noticed some resources and documentation contain the old ignore annotation from Flux 1. This explains why the jobs associated with these resources (the cdash migration job and gitlab RO user creation job) are continuing to run and fail in the cluster.
=> Update outdated Flux ignore annotations

k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
We've been seeing lots of evictions for gitlab pods, and it seems consolidation is the cause. Consolidation doesn't make sense for gitlab nodes anyway, since we only provide one instance type.
These changes are already applied to the cluster.
=> Switch to emptiness deprovisioning for gitlab nodes

k8s/production/karpenter/provisioners/runners/graviton/3/provisioners.yaml
https://aws.amazon.com/ec2/instance-types/m7g/
https://aws.amazon.com/ec2/instance-types/r7g/
=> Add m7g and r7g to our list of graviton3 instance families

terraform/modules/spack/gitlab_db.tf
`terraform plan` reports the `engine_version` of the postgres RDS instance to be `14.3` instead of `14`. This PR results in a no-op `terraform plan` for the RDS instance.
=> Update engine_version for gitlab postgres DB

k8s/production/runners/signing/release.yaml
Signing jobs can take awhile, and only allowing to run one at a time makes them run in serial, dominating the total time spent on protected pipelines (even those that rebuild few specs).  This PR allows up to 20 `sign-pkgs` jobs to run at a time, which should speed up protected pipelines significantly.
=> Increase concurrency of signing jobs

k8s/production/fluent-bit/release.yaml, terraform/modules/spack/opensearch.tf
The fluent-bit ServiceAccount is now outdated for the same reason as the notary ServiceAccount. Like #485, this PR encodes the IAM role into Terraform to avoid this from happening in the future.
=> Encode fluent-bit role into Terraform

k8s/staging/runners/kustomization.yaml, k8s/staging/runners/rm-secrets.yaml
#507 doesn't actually work, because I didn't add the `sealed-secrets.yaml` to the `resources` block in the staging kustomization. After doing that, I realized we also need to somehow exclude the other secrets in that YAML file from being included in staging. Documentation on how to remove an entire resources using kustomize seems very minimal, but I found this page that mentions how to do it and followed it https://pet2cattle.com/2022/11/kustomize-delete-resource. Unfortunately, the only way to find out if it works is to merge and see if Flux handles it ok.
=> Add sealed-secrets.yaml to runner staging kustomization

README.md, scripts/secrets/update.py
The secret update script will now open the user's configured editor (via the `$EDITOR` env var, defaults to `vim`) for inputting the secret value. This will solve the multi-line issue.
If anyone is on MacOS, please let me know how this works for you. I expect it to function the same, but I have no good way of testing it myself.
=> Use editor to input sealed secret values

k8s/staging/runners/kustomization.yaml
This secret is not needed for the staging cluster from what I can tell, so we need a patch to remove it as the staging sealed-secrets-controller will fail to decrypt it.
=> Remove unused sealed secret

terraform/modules/spack/elasticache.tf
Will allow us to bump the elasticache/redis version more easily. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster#engine_version
=> Manage elasticache engine/version with Terraform

.github/workflows/custom_docker_builds.yml, images/snapshot-release-tags/snapshot_release_tags.py, k8s/production/custom/snapshot-release-tags/cron-jobs.yaml
These should be annotated tags, but not releases on GitHub
=> Don't make releases for snapshot tags

k8s/production/prometheus/custom/pipeline-user-impact-dashboard.yaml
This is what the panel will look like now
This took some mucking around in grafana so I'm not 100% confident in the accuracy, but it seems to correlate how we'd expect with the "Packages by build time" pie chart.
@tgamblin Is this what you were expecting?
=> Add panel for CPU build time by package

.github/workflows/custom_docker_builds.yml, images/ci-key-rotate/rotate_gitlab_aws_access_keys.py, k8s/production/custom/rotate-keys/cron-jobs.yaml
The user `cray-binary-mirror` is associated with a permissions policy granting access to a new cray-only bucket.  This PR makes sure the users credentials get rotated along with all the others.
=> Rotate the credentials of another user

terraform/production/service_account_roles.tf
Follow up to #505. I incorrectly encoded the existing IAM policies as _inline_ policies, when they were actually _customer managed_ policies so this PR fixes this. I already did the necessary `terraform import` commands, so `terraform plan` produces a clean plan (aside from the DMS stuff that is in-flight).
=> Use user-managed policies instead of inline policies for IAM policies

k8s/staging/karpenter/kustomization.yaml
The instance region is the *3rd* element in the provisioner `requirements`, not 2nd.
=> Fix staging patch for pcluster provisioner

k8s/production/custom/unstick-pipelines/cron-jobs.yaml
This mitigation is currently not having the intended effect, as we have seen months-old pipelines still stuck in the "running" state, even with this cronjob running every three hours since forever.  We are also seeing multiple repeated develop pipelines (and pipelines for some PRs) running on the same sha.  Since this mitigation seems to be doing more harm than good, let's pause it until we can figure out what's wrong with it (or what's wrong with gitlab).
=> Suspend the stuck pipelines cronjob

.github/workflows/custom_docker_builds.yml, images/opensearch-index-build-logs/pipeline_logs_mapping.json5, k8s/production/custom/opensearch-index-build-logs/cron-jobs.yaml
The cronjob that crawls the build cache and records timing info, etc. into opensearch is currently failing. I thought #523 would fix it, but even after applying those changes it still fails. The error logs indicated that this .json5 is missing; my guess is that the old cluster was using the image from my fork (https://github.com/mvandenburgh/docker-images/pkgs/container/opensearch-index-build-logs) which does have that file, and when we switched to the new cluster, Flux reset it to the old image and it started failing.
=> Add missing json file to opensearch ingest image

k8s/production/prometheus/custom/ref-specific-statistics.yaml
Add a dashboard with panels taken from (or modeled after) existing panels in other dashboards, but restricted to a `ref` the viewer can specify.  This allows us to do a post-mortem on a release process, for example.
=> Add a dashboard viewing stats for specific refs

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
We seem to be using around 25% of our minio storage at the moment (that's where job traces are stored), and currently delete any job traces older than 30 days.  So it seems safe to increase the log output limit, and would reduce the number of jobs that exceed the limit, allowing to see the important parts of more job traces.
=> runners: increase log limit from 4MB to 10MB

k8s/production/monitoring/kubernetes-event-exporter/deployments.yaml
This will ensure the event-exporter doesn't get scheduled on ARM nodes or windows-based nodes.
=> Specify base node pool for event-exporter

images/gh-gl-sync/SpackCIBridge.py
Hopefully this will resolve the issue we've noticed where the sync script hangs waiting for a response from the GitLab API.
=> gh-gl-sync: timeout connections to GitLab API after 10 seconds

k8s/production/custom/gitlab-api-scrape/cron-jobs.yaml, k8s/production/custom/opensearch-index-build-logs/cron-jobs.yaml, k8s/production/custom/rotate-keys/cron-jobs.yaml, k8s/production/custom/skipped-pipelines/cron-jobs.yaml, k8s/production/custom/snapshot-release-tags/cron-jobs.yaml, k8s/production/custom/unstick-pipelines/cron-jobs.yaml
Make sure concurrencyPolicy and activeDeadlineSeconds are set for all our custom cron-jobs. This prevents our cron jobs from running longer than expected, and it prevents more than one copy of each job running at the same time.
=> Add protections to our custom cron-job.yaml files

k8s/production/custom/gh-gl-sync/cron-jobs.yaml, k8s/production/custom/gitlab-api-scrape/cron-jobs.yaml, k8s/production/custom/opensearch-index-build-logs/cron-jobs.yaml, k8s/production/custom/rotate-keys/cron-jobs.yaml, k8s/production/custom/skipped-pipelines/cron-jobs.yaml, k8s/production/custom/snapshot-release-tags/cron-jobs.yaml, k8s/production/custom/unstick-pipelines/cron-jobs.yaml
This belongs in the JobSpec, not the CronJobSpec
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#jobspec-v1-batch https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#cronjobspec-v1-batch
=> Put activeDeadlineSeconds in the right spot

.github/workflows/custom_docker_builds.yml, images/opensearch-index-build-logs/build_logs_to_opensearch.py, k8s/production/custom/opensearch-index-build-logs/cron-jobs.yaml
Currently, we first create a new pipeline-logs index before iterating through the build cache and adding any new builds to it. However if there are no new builds, the index sits there with zero documents. This adds logic to delete the index if this happens.
=> Delete pipeline-logs index if no records were added to it

k8s/production/prometheus/ingress.yaml, k8s/staging/prometheus/kustomization.yaml
This is follow on work from #548.
=> Move oauth2-proxy ingress to monitoring namespace

k8s/production/prometheus/release.yaml, k8s/staging/prometheus/kustomization.yaml
@mvandenburgh This should let prometheus pick up on exported prometheus metrics.
=> Add gitlab as a prometheus scraping target

terraform/production/s3.tf
Add a terraform section for maintaining S3 bucket policies for protected access to data.
The purpose of this addition is to prevent the download of package binaries which have license or other legal restrictions on redistribution. This issue may potentially be resolved by other means for the current list of packages, but a method for maintaining bucket policies with Terraform makes it easier to adapt to these constraints in the future as the come up.
**Note** I think these policies require further review to ensure we are remaining in compliance with the current bucket policies. 
CC: @AlmightyYakob @mvandenburgh @zackgalbreath @scottwittenburg
=> Terraform: Add S3 bucket policies for reading protected data

k8s/production/prometheus/oauth2-proxy.yaml, k8s/staging/prometheus/kustomization.yaml
We're currently pinned to v7.2.1 of oauth2-proxy due to https://github.com/oauth2-proxy/oauth2-proxy/issues/1724, and it appears the `github-org/repo` flag isn't working in that release due to https://github.com/oauth2-proxy/oauth2-proxy/pull/1650. For now I'm hardcoding usernames to who might reasonably want access and keeping an eye on oauth2-proxy updates.
=> Fix oauth2-proxy github configuration

terraform/production/s3.tf
The spack read file API is not using the AWS credentials for reading.
=> Disable s3 policies

k8s/production/custom/gitlab-setting-updater/cronjobs.yaml, k8s/production/custom/gitlab-setting-updater/serviceaccounts.yaml, k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
Note - this should not be merged yet. There are several intermediate upgrades that need to be performed with Flux turned off; this PR encodes what the final state of the cluster should be after the upgrade is complete.
=> Upgrade GitLab

k8s/production/gitlab/release.yaml
This will fix the issue where Redis pods occasionally get scheduled onto ARM-based nodes and fail. While I was reading the docs, I noticed Redis also has an option to export Prometheus metrics, so I went ahead and enabled that as well.
=> Specify node selector for gitlab redis pods

k8s/production/prometheus/release.yaml
Partially reverts #550. The node exporter should run on all nodes (that aren't Windows).
=> Stop constraining node-exporter pods

k8s/staging/custom/gitlab-setting-updater/kustomization.yaml
Follow up to #546 
This will enable the gitlab setting updater CronJob to run in staging.
=> Add kustomization for gitlab setting updater

images/upload-gitlab-failure-logs/taxonomy.yaml
Add a couple more patterns to search for to improve our classification rate.
Over the past week or so, we noticed an increase in the number of unclassified ("other") job failures.
=> Categorize more GitLab CI job failures

k8s/production/gitlab/certificates.yaml, k8s/production/gitlab/release.yaml, k8s/staging/gitlab/kustomization.yaml
We don't (no longer?) use the gitlab container registry, but instead use the github container registry. This PR updates the helm release for gitlab to disable the container registry; I applied this to staging with Flux disabled, and it applied cleanly and terminated the gitlab-registry pods as expected.
=> Disable gitlab container registry

k8s/production/spack/spackbotdev-spack-io/deployments.yaml
It seems the Redis host for spackbot dev was not updated properly when it changed in #479.
=> Fix redis host for spackbot dev

k8s/production/custom/gitlab-setting-updater/cronjobs.yaml, k8s/staging/custom/gitlab-setting-updater/kustomization.yaml
Fixes some issues I noticed with the gitlab updater -
- The relative paths to the production YAML files from #563 are off by one directory. This is causing flux to error when it tries to apply the latest changes from `main` to the cluster.
- By default, k8s keeps the previous three runs of cronjobs around in the pods list. imo we only need to see the most recent to be able to tell that it ran and succeeded, and keeping around two older pods just takes up space in the crowded `gitlab` namespace, so  I updated it to do that. (reference to docs: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#jobs-history-limits)
=> Fix relative path in staging kustomization

.github/workflows/custom_docker_builds.yml, images/cache-indexer/Dockerfile, images/cache-indexer/cache_indexer.py, k8s/production/custom/cache-indexer/cron-jobs.yaml, k8s/production/custom/cache-indexer/service-accounts.yaml, terraform/production/service_account_roles.tf
This builds a new image containing a python script that iterates over `s3://spack-binaries` to build a summary index describing all the mirrors that the cache.spack.io website should contain.  Then the image is used in a nightly cron job that builds the index and pushes to the root of the `s3://spack-binaries` bucket.
This still needs some updates to the `service_account_roles.tf` file to create a role granting read/write permission to the spack-binaries bucket.
=> Add cronjob to create binary cache summary index

k8s/production/kube-system/gp3-storage-class.yaml
This new StorageClass is a copy of our previous default except that `gp2` has been replaced with `gp3`.
=> Make gp3 the default StorageClass

.github/workflows/build_pcluster_amis.yml, terraform/modules/spack/eks.tf, terraform/modules/spack/karpenter.tf, terraform/modules/spack/variables.tf, terraform/production/github_actions_iam.tf, terraform/production/main.tf, terraform/staging/main.tf
Currently, we have a need to run a specific AMI on some of our gitlab runner nodes. This pcluster AMI was provided by Amazon and is not "[EKS-optimized](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-amis.html)". That is, it is not configured with the software needed for it to join an EKS cluster as a node. AWS provides a [Packer template](https://github.com/awslabs/amazon-eks-ami) that takes in a source AMI and builds a custom "EKS-optimized" version of that AMI. I did that using the pcluster AMI as the source AMI, and after pointing the pcluster Karpenter provisioner at the resulting "EKS-optimized" AMI, the nodes are able to join the cluster as expected. 
There is one caveat to this solution - the Packer template is coupled to the version of kubernetes running on the …
=> Proposed overhaul of building/deployment of custom pcluster AMIs

terraform/modules/spack/karpenter.tf
Follow on to #527 - underscores are not allowed in resource names. I also removed a local variable that is unused after #527.
I did a `terraform apply` and this applied successfully.
=> Fix invalid resource name

terraform/modules/spack/gitlab_db.tf
The gitlab DB is currently on `14.7` in both prod and staging, so this change serves to rectify the terraform code, and results in no infrastructure changes.
=> Set gitlab_db postgres version to 14.7

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
This change will ensure every pipeline build pod will have it's Job ID set as a pod label, which is useful for Prometheus metrics analysis.
cc @alecbcs
=> Add Job ID label to all build job pods

k8s/staging/kube-system/kustomization.yaml
Without this, staging is still defaulting to gp2.
=> Enable gp3 storage class in staging

.github/workflows/custom_docker_builds.yml, images/ci-key-rotate/rotate_gitlab_aws_access_keys.py, k8s/production/custom/rotate-keys/cron-jobs.yaml
Examination of recent failed pod logs shows that we are failing to updating gitlab ci variables that no longer exist.  This PR removes that IAM account from the list of those that get rotated.
<details>
<summary>Log excerpt</summary>
Note how it is the `develop-binary-mirror` iam account where we fail to update the gitlab ci variables.  Those are no longer present as they have been unused for the last year or so.
```
Traceback (most recent call last):
Begin IAM key rotation for user "pull-requests-binary-mirror"
Querying AWS IAM for access keys
Deleting old IAM access key
Creating new IAM access key
Updating GitLab to use new IAM access key
IAM key rotation for user "pull-requests-binary-mirror" complete!
Begin IAM key rotation for user "protected-binary-mirror"
Querying AWS IAM for …
```
=> Remove rotation of no-longer-used credentials

k8s/production/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/pcluster/graviton/3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
Currently we're being slightly inefficient with our pod scheduling, since we don't allow any sharing between "node pools". For example, if an `x86-64-v2` job is kicked off, it's able to run on any node provisioned by the `v2`, `v3` or `v4` provisioners, since it's compatible with all of those. However right now, it'll only be placed on nodes that are provisioned by the `v2` provisioner, which may lead to some wasted utilization if it could have fit on a `v3` or `v4` provisioned node.
=> Fix runner node selection

k8s/staging/gitlab/kustomization.yaml
=> Remove redis patch from gitlab HelmRelease

k8s/production/prometheus/custom/gitlab-pipeline-dashboard.yaml
This fixes a couple of panels in the "Pipeline Overview" dashboard, as they relied on a now out-dated label for nodes (removed in #446). 
The label selector has been changed to use a different node label, which accomplishes the same exact outcome, and has already been present since before the breaking change.
=> Fix pipeline dashboard label selectors

terraform/modules/spack/gitlab_runner_iam.tf, terraform/production/.terraform.lock.hcl, terraform/production/main.tf, terraform/production/secrets.tf, terraform/staging/.terraform.lock.hcl
Requires #601
This adds a GitLab OIDC provider to the spack module.
It also creates multiple resources for the protected and PR binary buckets*. The roles can only be assumed when the JWT matches the claims in `conditions`. This means that when a GitLab ID Token with `aud: protected_binary_mirror` is provided, it must also match the conditions here to be granted access.
This is a good illustration of how the overall flow works: https://docs.gitlab.com/ee/ci/cloud_services/index.html#authorization-workflow.
*The production bucket policies/roles aren't yet modularized in Terraform, so there's some logic to use the existing ones for production and create new ones for staging.
=> Add GitLab OIDC provider

k8s/production/runners/protected/graviton/2/release.yaml, scripts/gitlab_runner_pre_build/pre_build.py, scripts/gitlab_runner_pre_build/requirements.txt, terraform/modules/spack/gitlab_runner_iam.tf
Requires #602 
This adds a script for converting a GitLab JWT to AWS temporary credentials. It also adds runner-side configuration for bootstrapping and running the script before every job executes (see https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section). The URL for bootstrapping will change before merging to reference main.
=> Add GitLab runner pre_build_script for temporary credentials request

k8s/production/custom/gitlab-setting-updater/cronjobs.yaml
The size of the generated yaml for the E4S stack has grown beyond the current yaml size limit.  While we work on some optimization to decrease the size of the generated yaml, this PR makes sure we can still do a full rebuild of that stack.
=> Increase gitlab max_yaml_size_limit

k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
While performing this upgrade, we realized that the gitlab-runner helm chart images were pinned, which was causing the out-of-date runner versions we were seeing. 
@mvandenburgh According to the docs [here](https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/values.yaml?ref_type=heads#L3-4), the pin is unnecessary. Is that consistent with why the change was made in the first place?
=> Upgrade to Gitlab 16.3.2

k8s/staging/sentry/namespace.yaml, k8s/staging/sentry/release.yaml
Deploys Sentry to staging using a `HelmRelease`. This doesn't instrument any code or add the `sentry-kubernetes` controller yet, it just gets an instance of Sentry running. Once all of that is sorted out, I'll move this into production and refactor this into a `Kustomization` manifest.
=> Deploy Sentry in staging

.github/workflows/custom_docker_builds.yml, images/cache-indexer/cache_indexer.py, k8s/production/custom/cache-indexer/cron-jobs.yaml, k8s/staging/custom/cache-indexer/kustomization.yaml, terraform/modules/spack/cache_indexer.tf, terraform/production/service_account_roles.tf
This moves us closer towards having staging/prod parity by moving the cache_indexer into the spack terraform module. It also parameterizes the cron job so it can run in both environments.
=> Move cache indexer resources to spack module

.github/workflows/custom_docker_builds.yml, images/python-aws-bash/Dockerfile, images/python-aws-bash/requirements.txt
After a recent PR merge, I noticed the `python-aws-bash` image [failing](https://github.com/spack/spack-infrastructure/actions/runs/5753437333/job/15596635909#step:4:326) to build.
I think it was pinning `awscli` to an older version that was causing the build to hit this [issue](https://github.com/yaml/pyyaml/issues/601) with older versions of `pyyaml`.
As you can see in the deleted comment from this PR, there was a bug in older version of `boto3` that was preventing us from moving forward, but that bug has been fixed, and anyway spack had been [fixed](https://github.com/spack/spack/pull/31610) a year ago to support both older and newer versions of `boto3`.   So I thought we could move forward and remove all the pinning from these dependencies.
Just to be sure, I tested that I could …
=> Fix broken python-aws-bash image build

k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
@scottwittenburg I'm seeing PR builds succeed now. Example: `ctrl-f` for `pre-build` on the raw log of https://gitlab.spack.io/spack/spack/-/jobs/8215737.
=> Add pre_build_script to remaining runner configurations

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
This change adds the following information to the job metadata:
- package version
- compiler name
- compiler version
- arch
- package variants
These labels were added to the environment in https://github.com/spack/spack/pull/39905 (pending merge).
let me know if i'm missing anything
cc: @alecbcs @scottwittenburg
=> add additional job labels to all build job pods

k8s/production/gitlab/release.yaml
This will resolve the security warning that gets displayed on gitlab.spack.io.
=> Upgrade to GitLab 16.3.4

k8s/staging/prometheus/kustomization.yaml
This explains why https://grafana.staging.spack.io/ (and related URLs) return an invalid cert error.
=> Fix selectors for prometheus in staging kustomization

k8s/production/ingress-nginx/release.yaml
Increases the memory request for nginx from 100 MB to 1 GB.
=> Increase memory request for nginx pods

scripts/gitlab_runner_pre_build/pre_build.py, scripts/gitlab_runner_pre_build/test_pre_build.py
This adds retries to the OIDC assume role script in the event that a transient error occurs, or worse, gitlab.spack.io is down momentarily while AWS is fetching the identity information.
@scottwittenburg PTAL. In particular, I'm not sure how long we should be sleeping and retrying.
=> Add retries to pre_build.py

k8s/production/gitlab/release.yaml, k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
Resource request values came from here:
https://karpenter.sh/docs/concepts/instance-types/#m54xlarge
They were selected so that gitaly would get the whole m5.4xlarge node to itself.
=> Run gitaly by itself on a m5.4xlarge instance

k8s/production/gitlab/release.yaml, k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
Resource request values came from here:
https://karpenter.sh/docs/concepts/instance-types/#m54xlarge
They were selected so that gitaly would get the whole m5.4xlarge node to itself.
Note that karpenter is telling us that our daemonsets add approximately 5 GB RAM in overhead.
=> Run gitaly by itself on a m5.4xlarge instance (take 2)

k8s/staging/runners/kustomization.yaml
Currently, we only include a subset of our AWS runners in our staging gitlab setup. This PR adds the rest of the public runners to staging to bring it closer to parity with production.
=> Add missing public runners to staging

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml, terraform/modules/spack/sentry.tf
This should catch any system errors on gitlab runners in sentry. @mvandenburgh It turns out this is a global config, not in the runners toml, so we can use a config map for it.
=> Add sentry_dsn for gitlab runners

k8s/production/gitlab/release.yaml
I tested this on staging and confirmed that (1) this exposes metrics at the expected endpoint, and (2) the gitaly/gitlab helm chart adds the correct annotations to the gitaly pod for prometheus to auto discover it as a scrape target.
=> Enable Prometheus metrics for Gitaly

k8s/production/gitlab/release.yaml, k8s/production/prometheus/release.yaml
Prometheus is supposed to discover and scrape service monitors automatically, but it only looks in the namespace it's deployed in by default. This configures it to search all namespaces in the cluster. The `kube-prometheus-stack` docs didn't go into detail on this, but [this issue](https://github.com/prometheus-community/helm-charts/issues/106#issuecomment-700847774) helped me get this working.
After merging #663 , I noticed it didn't work in production. When I was messing around in staging, I manually configured gitaly in the `additionalScrapeConfigs` block in the prometheus helm release before trying to figure out the auto-discovery thing. I think what happened is that it was still falling back on the `additionalScrapeConfigs` even after I removed it, and I wrongly assumed it was …
=> Allow Prometheus to scrape ServiceMonitors in any namespace, enable ServiceMonitor for gitaly

k8s/production/gitlab/pod-cleanup.yaml
Flux is failing to apply the added resources from #660, seemingly due to the order of listed resources.
=> Re-order resources in gitlab pod-cleanup

terraform/modules/spack/binary_mirrors.tf, terraform/modules/spack/modules/binary_mirror/cloudfront.tf, terraform/modules/spack/modules/binary_mirror/variables.tf, terraform/production/main.tf
This codifies the state of the cloudfront deployment on production now. The diff against production has a couple of rough patches, so applying this will have to be done carefully.
@mvandenburgh FYI:
1. ACM certs for CF have to be created in us-east-1
2. The cache policy can't be encapsulated in the binary mirror module since it has to be used by both instances
=> Add CloudFront distributions for binary mirrors

.github/workflows/build_pcluster_amis.yml, terraform/production/github_actions_iam.tf
The pcluster AMI build workflow is failing on `main` due to the Terraform version being out of date. This PR just removes the use of Terraform from that workflow all together. 
Practically, we never upgrade k8s by merging a PR to `main`. So it's not necessary to run this action on every push. Instead, it now runs by a manual invocation, where the k8s version is provided by the user instead of being pulled from TF state.
=> pcluster workflow: get k8s version from workflow_dispatch input

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/requirements.txt, k8s/production/custom/gh-gl-sync/cron-jobs.yaml, terraform/modules/spack/sentry.tf
Adds Sentry to the sync script for error reporting. I've parameterized things such that if (1) the sentry sdk is not installed, or (2) there's no SENTRY_DSN environment variable set, then the sync script still works as usual.
=> Add Sentry integration to sync script

k8s/production/prometheus/custom/build-timing-dashboard.yaml
Add a dashboard with panels showing top offenders for:
- per-pkg phase times summary for:
* installs from cache
* installs from source
- per-pkg times for installing from source vs installing all dependencies
- per-pkg fetch from cache times
=> Encode Grafana build timing dashboard in k8s

.github/workflows/custom_docker_builds.yml, analytics/requirements.txt, analytics/settings.py, images/build-timing-processor/app.py, images/build-timing-processor/job-template.yaml, images/build-timing-processor/requirements.txt, images/cache-indexer/Dockerfile, images/cache-indexer/cache_indexer.py, images/cache-indexer/requirements.txt, images/gitlab-error-processor/app.py, images/gitlab-error-processor/job-template.yaml, images/gitlab-error-processor/requirements.txt, images/gitlab-skipped-pipelines/requirements.txt, images/gitlab-skipped-pipelines/skipped_pipelines.py, images/snapshot-release-tags/requirements.txt, images/snapshot-release-tags/snapshot_release_tags.py, images/upload-gitlab-failure-logs/requirements.txt, images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py, k8s/production/custom/build-timing-processor/deployments.yaml, k8s/production/custom/cache-indexer/cron-jobs.yaml, k8s/production/custom/gitlab-error-processor/deployments.yaml, k8s/production/custom/skipped-pipelines/cron-jobs.yaml, k8s/production/custom/snapshot-release-tags/cron-jobs.yaml, terraform/modules/spack/sentry.tf
Adds Sentry integration to the rest of the custom Python jobs that run in the cluster.
I didn't instrument any of the build time processor stuff in this PR because I'm not as familiar with how that one works. I'll make a follow up PR for that and consult with @AlmightyYakob on the best way to do that.
=> Instrument other cluster python jobs with Sentry

k8s/production/prometheus/custom/runner-pressure.yaml
Adds a dashboard with panels attempting to show pressure on selected groups of runners over time.  The queries are addressed to the gitlab database, and find jobs that ran on UO runners using three different `WHERE` clauses:
1. darwin/arm64: `ci_runner.platform LIKE 'darwin' AND ci_runner.architecture LIKE 'arm64'`
2. ppc64le: `ci_runners.architecture LIKE 'ppc64le'`
3. cray:  `ci_runners.description LIKE 'uo-gary%'`
4. aws: `ci_runners.description LIKE '%-gitlab-runner-%'`
Only jobs with a non-null `started_at` are selected, and results are binned up by that value into 5 minute intervals.  Average seconds in pending state is computed for the jobs in each bin and plotted as well.
=> Add dashboard tracking pressure on selected  groups of runners

terraform/production/gitlab_webhooks.tf
This produces a clean plan when running `terraform plan` against production.
=> Encode gitlab webhooks into Terraform

.github/workflows/custom_docker_builds.yml, images/gitlab-error-processor/job-template.yaml, images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py, k8s/production/custom/gitlab-error-processor/deployments.yaml
If the `runner` key is nonexistant in the job payload, the python script will crash and no record will be uploaded to opensearch. Since adding Sentry to this job last week, we've seen this happen several times. It seems the `runner` key may be missing when there is a "runner system failure", but unfortunately gitlab does not appear to provide an exact spec for the structure of this JSON blob.
=> Fix crash in gitlab error processor upload job

.github/workflows/custom_docker_builds.yml
This will make it so a "test build" of docker images (i.e. they will get built but not published to GHCR) gets performed on any PR that makes changes to the `images/` directory. This will help catch image build failures before a merge to `main` happens.
=> Test docker image builds on PRs

k8s/production/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/pcluster/graviton/3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/testing/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml
Update our Karpenter provision to apply taints to our pipeline nodes. This will prevent other pods from being scheduled on them.
Also update our GitLab runner configuration to allow our pipeline pods to tolerate these taints.
=> Taint pipeline nodes

.github/workflows/custom_docker_builds.yml, analytics/analytics/management/commands/upload_build_timings.py, images/build-timing-processor/job-template.yaml, k8s/production/custom/build-timing-processor/deployments.yaml
There are a couple of things that are causing the analytics DB to not contain the added fields from #635 
1. I forgot to add the `@contextmanager` decorator to the `get_job_artifacts_file` function. The lack of this decorator _should_ have caused sentry errors that would point to the issue. However, that didn't happen because...
2. Due to the fallout of #635 regarding version collision, the hastily made follow-up PR #690 didn't actually bump the version of `upload-build-timings` that was used in the build timing webhook. So events that were being sent to the webhook were _still_ using the old version of the script, and not adding in those fields.
=> Fix build timing script and image versions

terraform/modules/spack/opensearch.tf, terraform/modules/spack/variables.tf, terraform/production/main.tf, terraform/staging/main.tf
This adds a basic auth deployment of opensearch to staging instead of using cognito. Setting up a separate cognito deployment would have been significantly more work. This opensearch deployment is also a bit different in specific configurations that still have to be fully codified in terraform, but it gets us closer to staging/production parity.
I think deployment for this change will need special attention paid to the password resource to avoid changing it in production, see https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password#import.
=> Add opensearch staging deployment

.gitignore, scripts/secrets/update.py
I experienced some frustration recently when using the secret update script. I've modified it to include the following behavior:
1. When updating a secret, if possible, the existing secret value is de-crypted and injected into the editor before being opened for the user. This makes it much easier to both update a _part_ of a secret, as well as fix any errors. Previously, to do this you had to go through the process of fetching a secret from the cluster, decoding it, copying that value and pasting it into the editor, and then finally changing what you needed. This has multiple times now caused me issues with character escaping, etc., which this new approach avoids.
2. Since there are actually multiple key pairs which can be used to encrypt/decrypt values (relevant …
=> Improve functionality of sealed secrets update script

k8s/production/prometheus/release.yaml
#630 added some job information to be exposed through attributes. In that PR, I tried including the entire `metrics` section by doing this:
```
metricAnnotationsAllowList:
- pods=[gitlab/ci_job_id,metrics*]
```
However, I checked the [docs](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md#available-options) and it seems like the only options are specifying each annotation manually or including all (performance isn't great). See [this prometheus query](https://prometheus.spack.io/api/v1/query_range?query=kube_pod_annotations%7Bannotation_gitlab_ci_job_id=%279359381%27%7D&start=1701780555&end=1701800555&step=10) for an example of this not working.
This PR lists each annotation we would like to have available in prometheus.
Is there a way to test if this would …
=> Fix pod annotations

.github/workflows/custom_docker_builds.yml, images/gitlab-error-processor/job-template.yaml, images/upload-gitlab-failure-logs/upload_gitlab_failure_logs.py, k8s/production/custom/gitlab-error-processor/deployments.yaml
In certain error scenarios, we were trying to index a `None` value.
=> Fix crash in error taxonomy upload script

.github/workflows/custom_docker_builds.yml, images/ci-key-rotate/rotate_gitlab_aws_access_keys.py, k8s/production/custom/rotate-keys/cron-jobs.yaml
All runners should now be using OIDC for authentication. I'm going to disable the secret updating and verify that nothing breaks. After a little while I'll remove all the associated key rotation code.
=> Disable gitlab aws access key rotation

.github/workflows/custom_docker_builds.yml, images/gitlab-error-processor/job-template.yaml, images/upload-gitlab-failure-logs/taxonomy.yaml, k8s/production/custom/gitlab-error-processor/deployments.yaml
This should help us track a broader set of AWS access errors seen in runners without OIDC configured.
=> Add AWS AccessDenied to the error taxonomy

.github/workflows/custom_docker_builds.yml, k8s/production/custom/webhook-handler/deployments.yaml
Follow up to #723 
When I included the internal prometheus URL as an env var to the deployment, I forgot to include the protocol (`http`) on the front of it.
=> Include protocol in webhook handler prometheus url

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/prometheus.py, analytics/analytics/models.py, k8s/production/custom/webhook-handler/deployments.yaml
We were seeing a few issues in sentry from the new job processor work (#723). This PR fixes the following issues:
1. A typo that was causing non-aws jobs to fail to be tracked correctly
2. A bug in handling node model creation
3. Issues resulting from static step sizes in range queries. This is because if a job is sufficiently short (a minute or less), the previous step size of 30 seconds could result in just one or even zero samples, depending on the start and end times used. Now, dynamic step sizes (based on the job duration) are used.
=> Misc bug fixes for job processor prometheus logic

k8s/production/prometheus/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml
This is a follow-up to #630. With the exception of stack name, all the information I need to retrieve for the dynamic allocation web hook is available in the annotations. Rather than add load to the Prometheus server with an extra request to the labels, it would be most convenient to have the stack name available here as well.
@jjnesbitt
=> Add stack name to annotations

analytics/analytics/settings/development.py
This allows services running inside the docker network to communicate with the django server with the docker `django` dns name.
=> Add docker-compose `django` service to ALLOWED_HOSTS (dev only)

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/models.py, analytics/analytics/job_processor/prometheus.py, k8s/production/custom/webhook-handler/deployments.yaml
Follow up  to #740 
One of the fixes in that PR was to prevent duplicate results from prometheus queries when filtering by `pod`. That was accomplished by including a filter for a non-empty `node` field, which I _thought_ would guarantee we only get results for the pod once it's running on the node. However, that turns out not to be the case. It seems the pod can be present on the node _before_ the pod has an IP address, which results in two values for the same pod from the query.
To fix this, an additional filter for `pod_ip` has been added.
The following fixes have also been made:
1. A transaction has been added around node creation, to avoid a `TransactionManagementError` that was being raised.
2. Fix an incorrect raising of `UnexpectedPrometheusResult`
=> Further prometheus job processor fixes

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/__init__.py, analytics/analytics/core/job_log_uploader/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
We've seen these jobs fail occasionally during spikey job finishes.
=> Automatically retry job log processing

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
This should allow larger job logs to get through and let us retrieve more detail about what went wrong. Assuming there's no stability issues after rollout, we might want to ask 3rd party runners to do the same.
=> Increase the job log limit to 20MB

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
This removes the `retried` field and adds the following fields to opensearch:
```
is_retry: bool
is_manual_retry: bool
attempt_number: int
final_attempt: bool
```
Computing these is a little trickier than it ought to be but this should account for less common situations e.g.
1. Jobs with unique retry conditions unlike the regular rebuild job (like protected publish)
2. Multiple pipelines (`commit_id`s) executing the same named job multiple times
3. Webhooks being received/processed out of order
@mvandenburgh I know this is going to go in postgres soon but I wanted to get the logic committed so it can be ported when that happens.
=> Enhance retry metadata tracking

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_log_uploader/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
Follow on to #757 so this can be tracked for all jobs, not just failed rebuild jobs.
=> Add retry metadata to all job logs instead of just failures

analytics/docker-compose.yml
The GitLab Container Registry is enabled by default, but is currently inaccessible outside of the `gitlab` docker container. This PR exposes the registry internally on the docker compose network at `http://gitlab:5050`.
[Docs](https://docs.gitlab.com/ee/administration/packages/container_registry.html#configure-container-registry-under-an-existing-gitlab-domain)
=> (docker compose) Expose gitlab container service internally

k8s/production/gitlab/certificates.yaml
This should effectively disable the automatic renewal of the gitlab certificates by cert-manager. Manual renewals are going to be done going forward to ensure that the OIDC configuration is updated in tandem.
See also:
- https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificateSpec 
- https://cert-manager.io/docs/reference/cmctl/#renew
=> Reduce the frequency of gitlab tls certificate renewals

k8s/production/aws-node-termination-handler/release.yaml, k8s/production/cert-manager/release.yaml, k8s/production/efs-csi-driver/release.yaml, k8s/production/fluent-bit/release.yaml, k8s/production/gitlab/release.yaml, k8s/production/ingress-nginx/release.yaml, k8s/production/prometheus/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml, k8s/production/sealed-secrets/release.yaml, k8s/production/sentry/release.yaml
The Flux changelog mentions that `v2beta1` is deprecated and will soon be removed from Flux - https://github.com/fluxcd/flux2/releases/tag/v2.2.0. I'm also seeing a deprecation warning whenever I apply a HelmRelease YAML with kubectl.
Note: we're currently running Flux v2.2.2.
=> Upgrade to `v2beta2` of `HelmRelease` kind

terraform/modules/spack/analytics_db.tf, terraform/modules/spack/cdash_db.tf, terraform/modules/spack/eks.tf, terraform/modules/spack/gitlab_db.tf
Some AWS resources got changed out from under Terraform, some due to AWS upgrades and some due to some manual actions in the AWS console UI, so this is just bringing the Terraform state up to date with reality.
One exception to this is enabling performance insights for each RDS instance. I had enabled it a while back for the prod gitlab instance for debugging, and I think it's worth enabling for all of our instances since it's free (at least for the default retention rate of 7 days), and might be helpful someday.
=> Update terraform state with reality, enable RDS performance insights

.github/workflows/terraform-drift-detection.yaml
From the [github actions docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule):
> The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. If the load is sufficiently high enough, some queued jobs may be dropped. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
I set it to run the 16th minute of every hour, hopefully that helps.
=> Change cron job time for infra drift workflow

k8s/staging/gitlab/kustomization.yaml
Currently, the resource allocation for the gitlab web server is as follows:
- Production: we always run a minimum of 4 web server pods, and autoscale up to 16 pods when needed
- Staging: we always run a minimum of 1 web server pod, and do not allow any autoscaling. Additionally, we set reduced CPU/memory requests as compared to prod
This PR updates staging to
- Allow it to scale up to the same amount of pods allowed in prod
- Remove the smaller CPU/memory requests and align it with those in prod instead
I left the minimum number of pods set to 1, since there's not really a need to run 4 pods at _all_ times in staging.
This should help alleviate some of the issues @johnwparent observed while testing windows CI in staging.
=> Align gitlab staging resource limits with production

k8s/production/prometheus/release.yaml
Luckily there were not changes to the Helm chart values.yaml, so this was relatively straightforward to do. 
The only other change I made in https://github.com/spack/spack-infrastructure/commit/7f3c5800a01a9fd0817d724ef3d98af0bfcaa543 is to tell Flux to automatically handle upgrading CRDs when the chart is upgraded, as opposed to me needing to run all these CRD upgrade commands on each version jump - https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#upgrading-an-existing-release-to-a-new-major-version
=> Upgrade `kube-prometheus-stack` to the latest chart version

k8s/staging/runners/protected/windows/x86_64/v2/release.yaml, k8s/staging/runners/public/windows/x86_64/v2/release.yaml, scripts/gitlab_runner_pre_build/pre_build.py
Updates Windows runner prescript to generate `envvars` as a `.ps1` file, source it with powershell, and refactors the pre build Python script to generate powershell compatible export commands
Removed the logic searching for Python at the beginning of the setup script, Python is just `python` on Windows.
CC @kwryankrattiger @mvandenburgh  
Please let me know if I need to update something else to be compatible with this.
=> Karpenter Windows Runners: source envvars file

k8s/staging/runners/protected/windows/x86_64/v2/release.yaml, k8s/staging/runners/public/windows/x86_64/v2/release.yaml
Multiline strings and double quotes were functional when run from a script directly but seem to cause issues with the TOML and other parsing this attribute is passed through before being composed into the step script. 
Remove those elements.
CC @kwryankrattiger
=> Don't use multiline string or double quotes

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/__init__.py, analytics/analytics/core/job_log_uploader/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
Given that opensearch seems to struggle during periods of high traffic, this increases the retry parameters to allow tasks to take a bit longer to settle. `retry_jitter` was already enabled, I just added it to make it a bit more explicit that we won't be subject to a thundering herd problem.
=> Increase retries for jobs that use opensearch

.github/workflows/validate-terraform.yaml
I noticed this workflow was running on PRs that don't modify any TF code.
=> Only run TF validate workflow if PR touches terraform

.github/workflows/terraform-drift-detection.yaml
Hopefully this cuts down on the amount of false positives we get from the drift detection job due to transient network failures on the `terraform init` step.
=> Add retries/exp. backoff to TF init

k8s/production/gitlab/release.yaml
See https://docs.gitlab.com/ee/administration/reference_architectures/3k_users.html#cluster-topology
The 3k users tier is the minimum requirements for a gitlab deployment to be considered "high-availability" and is what we followed when provisioning other AWS resources such as postgres in RDS and redis in elasticache.
=> Align gitlab webservice/sidekiq resource requests with recommended values

k8s/production/custom/skipped-pipelines/cron-jobs.yaml, k8s/production/fluent-bit/release.yaml, k8s/production/metabase/metabase-deployment.yaml, k8s/production/metabase/postgres-deployment.yaml, k8s/production/monitoring/kubernetes-event-exporter/deployments.yaml, k8s/production/prometheus/oauth2-proxy.yaml
A couple deployments in our cluster are either underprovisioned or have no resource requests at all. I started going through some of them and increased/added new resource requests accordingly.
I confirmed these values over the last 7 days using this dashboard https://grafana.spack.io/d/12141241231232/used-7c-wasted-resources?orgId=1&refresh=1m&var-prometheus=prometheus&var-namespace=pipeline&var-app=All&var-instance=All&from=now-7d&to=now and prometheus.
=> Update resource requests/add missing ones

k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
This is the instance type recommended by gitlab for the webservice. https://docs.gitlab.com/ee/administration/reference_architectures/3k_users.html#cluster-topology
It seems Karpenter is having trouble scheduling the webservice pods after #817 . Giving it this instance type should fix that.
=> Add `c5.4xlarge` instance type to `gitlab` provisioner

k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
As I mentioned here https://github.com/spack/spack-infrastructure/pull/819#issuecomment-2059910506, the gitlab webservice requires 16.4 vCPUs (so really, 17) to run, as [the recommended specs from gitlab](https://docs.gitlab.com/ee/administration/reference_architectures/3k_users.html#cluster-topology) themselves is 16 vCPUs, but I didn't account for the approximately 0.4 vCPUs for daemonsets that must also run on the node. 
The `c6a.8xlarge` instance is the cheapest one I could find that has the required CPU and is also x86-based (gitlab web service does not have an ARM image), so I picked that one. https://instances.vantage.sh/?min_vcpus=17
Karpenter will hopefully be smart enough to schedule a bunch of other gitlab pods on this instance next to the webservice so that the increased …
=> Add c6a.8xlarge to gitlab provisioner

k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
This is no longer needed now that we've lowered gitlab webservice resource requests #838. I disabled flux and removed this in the cluster, and the pods were still schedulable.
=> Remove `c6a.8xlarge` from gitlab provisioner

k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/staging/runners/kustomization.yaml
This PR makes the necessary changes to spin up Windows GitLab runners on gitlab.spack.io. All of the work needed to allow Karpenter/k8s to run windows nodes was already done and applied by #764; this PR just moves the existing staging runners to production.
I noticed a few inconsistencies in the runner config YAML when compared to the linux public/protected x86 v2 (likely due to changes in the latter since the staging windows runners were created), so I also updated that to be consistent.
attn @johnwparent @kwryankrattiger
=> Add windows runners to gitlab.spack.io

k8s/production/gitlab/release.yaml
As of #838, we request 7GB for each gitlab webservice pod. We've been seeing sporadic downtime of a few seconds on gitlab.spack.io for the last week, and it looks like memory usage has been at about 14 GB for each gitlab webservice pod that period of time
https://grafana.spack.io/d/d249cc23-6930-403e-91f6-c9c30389b88d/kubernetes-deployment-cpu-and-memory-metrics
I verified that Karpenter can spin up necessary nodes to accomodate this without adding new instance types.
=> Increase memory request/limit for gitlab webservice

terraform/modules/spack/eks.tf, terraform/modules/spack/github_actions_iam.tf
This allows us to grant individual IAM users read-only access to the cluster. I also moved all IAM users that haven't accessed the cluster in a long time to the read only group.
I applied this to staging already and verified that it works.
=> Add read-only cluster group

terraform/modules/spack/cdash_db.tf
The instance type we use for staging doesn't support performance insights, so a terraform apply off of main on staging currently fails.
=> Only enable performance insights on cdash prod DB

k8s/production/spack/gantry-spack-io/stateful-sets.yaml
=> Add service account to spack-gantry statefulset

k8s/production/custom/protected-publish/cron-jobs.yaml
This pod may have run up against memory pressure recently, so request more memory in the hopes that kube will mostly give it a node of its own.
=> Bump memory request of protected-publish cron job

k8s/production/custom/protected-publish/cron-jobs.yaml, k8s/production/karpenter/provisioners/base/provisioner.yaml
The `m4.large` instance type has 2 vCPU and 8 GB memory, so let's try that type and request most of that memory for this job.
=> Increase resources for protected-publish again

k8s/production/custom/gitlab-restart-webservice/cronjobs.yaml, k8s/production/custom/gitlab-restart-webservice/serviceaccounts.yaml
This will help mitigate the issue we've seen where the GitLab webservice consumes more and more memory as time goes on, which eventually results in spurious CI job failures.
The relevant upstream issue appears to be:
https://gitlab.com/gitlab-org/gitlab/-/issues/432847
=> New cron job to restart gitlab-webservice once a day

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml
This is needed for the upcoming analytics DB re-work and figured it made sense to split it out.
=> Add job spec hash as pod annotation

terraform/modules/spack/gitlab_webhooks.tf
The error processor has been consolidated into the main GitLab webhook, so this is no longer needed (and results in a bunch of spammy errors in opensearch).
=> Remove unused GitLab webhook

terraform/modules/spack/eks.tf
Reverts part of #840 that broke the drift detection job.
=> Add github actions group back to aws_auth configmap

k8s/production/sealed-secrets/release.yaml, terraform/modules/spack/eks.tf, terraform/modules/spack/karpenter.tf, terraform/production/flux.tf, terraform/production/main.tf, terraform/staging/flux.tf, terraform/staging/main.tf
I've already applied the updates in the AWS console, this PR just syncs up the Terraform with it. 
I also discovered a bug in the way we schedule "bootstrapping" pods, i.e. pods that must come up first before any others (most notably, Karpenter). We provision an initial managed node group to allow Karpenter pods to be scheduled, and then they are responsible for provisioning any other needed compute capacity. But because we don't taint the nodes in that node group, it's possible for other nodes to fill it up and block Karpenter from ever getting scheduled. 
As part of this PR, I added a taints and tolerations for those nodes such that Karpenter, Flux, and the sealed-secrets controller are the only pods allowed to be scheduled on them; all other pods must wait for a Karpenter-provisioned …
=> Upgrade EKS clusters to 1.29, fix scheduling issue with bootstrap pods

k8s/production/ingress-nginx/release.yaml
This configures fluent-bit to parse ingress-nginx logs and store them in a more structured format in opensearch. Currently, a log record from ingress-nginx looks like this:
```
{
"log": "192.168.38.176 - - [19/Jun/2024:18:29:59 +0000] "POST /api/v4/runners/verify HTTP/1.1" 200 67 "-" "gitlab-runner 16.11.1 (16-11-stable; go1.21.9; linux/amd64)" 335 0.026 [gitlab-gitlab-webservice-default-8181] [] 10.100.182.194:8181 67 0.027 200 0fb16c52659a7c780187d4c1cfb7836c",
}
```
With this change, it will look like this:
```
{
"log_processed.agent": "Go-http-client/2.0",
"log_processed.code": 401,
"log_processed.host": "192.168.211.104",
"log_processed.method": "GET",
"log_processed.path": "/api/v4/projects/2/jobs?per_page=100&page=25&scope[]=failed&scope[]=success&scope[]=canceled", …
```
=> Configure fluent-bit to parse ingress-nginx logs format

k8s/staging/prometheus/kustomization.yaml
The missing "https://" from various urls in the staging patch config seems to have caused the issue.
=> Fix prometheus/grafana in staging

k8s/production/prometheus/release.yaml
This was added in #865 but never added to the prometheus annotation allow list, which means it's still not being reported by prometheus.
=> Allow "metrics/spack_job_spec_hash" annotation

k8s/production/custom/gh-gl-sync/cron-jobs.yaml, k8s/production/custom/gh-gl-sync/service-accounts.yaml
After moving the PR branch cleanup to the spack bot this service account is not longer needed for the sync script.
=> Drop unused service account

k8s/production/prometheus/custom/gitlab-ci-failures-dashboard.yaml
This points Grafana at the new `gitlab-job-failures-*` index pattern I created to use the proper timestamp (`build_created_at` instead of the time at which the webhook is fired) for failed CI jobs,
=> Update data link to new opensearch index

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/production/custom/gh-gl-sync/cron-jobs.yaml
GitLab's recent reliability issues have caused the sync script to fail fairly regularly. This change adds retries to the sync script to mitigate the impact of these failures. Hopefully this will improve things until we get to the bottom of this.
=> [gh-gl-sync] instrument gitlab requests w/ retries

k8s/production/custom/protected-publish/cron-jobs.yaml, k8s/production/karpenter/provisioners/base/provisioner.yaml
The protected-publish job is failing (albeit infrequently) when it uses more memory than requested and triggers the node to become low on memory, which results in eviction.
The two times I saw evictions, it was using just over 7GB, so this doubles the request from 6GB to 12GB.
To support this, we need to move up to the next instance size in karpenter, so from `m4.large` to `m4.xlarge` which doubles available cores and memory to 4vcpu and 16GB.
=> Increase resources available to protected-publish

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
The `Soft time limit (60s) exceeded for upload_job_failure_classification` sentry errors seem to be occuring due to the gitlab API requests hanging. The [default timeout for them is `60`](https://github.com/python-gitlab/python-gitlab/blob/main/gitlab/config.py#L108), so if a request hangs for that long, it will exceed the Soft time limit set in the celery task. 
Adding this timeout of 15 seconds will hopefully confirm this, as I don't see a way to see what's happening using just the sentry errors.
=> Add timeout to gitlab requests in job classification task

.github/workflows/custom_docker_builds.yml, analytics/Dockerfile, analytics/analytics/job_processor/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
Instead of cloning the full repo and then checking out a specific tag, we can use `--depth 1` to only clone the desired tag.
=> Speed up `spack` git clone in docker build

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/__init__.py, analytics/analytics/job_processor/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
Adds retries to error classification and process_job celery tasks on `requests.exceptions.ReadTimeout` exceptions. These happen when a request to gitlab times out.
=> Retry celery tasks on gitlab timeouts

k8s/production/ingress-nginx/release.yaml
Since there's some evidence that the nginx controller pod is being killed with a `SIGTERM` periodically, requiring at least two to be up at all times could help mitigate this issue.
=> Require at least two replicas for nginx controller

.github/workflows/custom_docker_builds.yml, images/ci-prune-buildcache/ci_buildcache_prune.py, k8s/production/custom/prune-buildcache/cron-jobs.yaml
Add option to fail fast for local testing/usage. By default the script will attempt all mirrors and write errors/failures to a file
Fix bug where error/failures files were not being opened for write.
=> Fix error handling in pruning script

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/prometheus.py, k8s/production/custom/webhook-handler/deployments.yaml
When karpenter spins up a new node to accommodate a job, the prometheus query can return two series instead of one. The first one for a short period of time, while the node is still initializing. The second one, after the node is finished initializing, contains an extra karpenter label indcating so (`label_karpenter_sh_initialized='true'`), which "splits" up the data into two series. This PR adds a filter to only return results containing the karpenter label.
=> Fix issue with retrieving prometheus node labels in job processor

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/prometheus.py, k8s/production/custom/webhook-handler/deployments.yaml
Follow up to #910 
Turns out there's yet another node label that is added after a node is initialized. This led to the same error cropping up in sentry for the same reason as before. This _seems_ to be the last instance of this problem, so merging this should finally resolve this issue.
=> Add another filter to prometheus node label query

terraform/modules/spack/karpenter.tf
I applied this to staging, and tested it by deleting a bunch of nodes and Karpenter was able to spin them back up.
See https://karpenter.sh/v0.37/upgrading/upgrade-guide/#upgrading-to-0310 for the changelog - nothing impacts us, so this is a relatively straightforward upgrade. Upgrading to 0.32.0 does contain a fair amount of breaking changes, so I've left that for a follow up PR.
=> Upgrade Karpenter to 0.31.4

terraform/modules/spack/karpenter.tf
Upgrades the Terraform EKS karpenter module to 19.21.0. This just adds a few IAM permissions that are required for karpenter 0.32.0+.
=> Upgrade TF `karpenter` module to 19.21.0

.github/scripts/check_docker_image_versions.sh, .github/workflows/check_docker_image_versions.yml
(I accidentally closed #912 when playing around with git commands locally)
This PR adds a CI workflow that fails if it finds one of the following conditions:
1. A directory was modified, but the image version in `.github/workflows/custom_docker_builds.yml` was not incremented
2. A directory was modified, and the image version in the workflow file was bumped, but uses of the old image version still remain in the code base.
In cases where this check is either undesired or unhelpful, the `no-image-bump` tag can be applied to the pull request and the job will be skipped.
=> Add CI workflow to check for missing image version bumps

.github/scripts/check_docker_image_versions.sh
- Add `^` to front of regex for directory changes
- Escape all strings used for search
=> Fix search pattern escaping in image check workflow

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
Jobs like [this one](https://gitlab.spack.io/spack/spack/-/jobs/11963760) are getting categorized as `other`, when they should be
`concretizer_error`. This PR adds a new regex to the taxonomy fix this.
I tested this locally and it works as intended against that job trace.
=> Add new regex to concretizer_error taxonomy

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
Jobs like [this one](https://gitlab.spack.io/spack/spack/-/jobs/11966614) are getting categorized as `other`, when they should be
`concretizer_error`. This adds a new regex to the taxonomy fix this.
Hopefully this and #923 cover all the new job errors we've seen today
=> Add (another) new regex to `concretizer_error` taxonomy

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
This correctly categorizes the error that occurs when a `rebuild-index` job fails due to a missing spec list, which happens when all dependent jobs fail. Currently, that error is getting labeled as `other`.
Example jobs:
https://gitlab.spack.io/spack/spack/-/jobs/11980518
https://gitlab.spack.io/spack/spack/-/jobs/11980519
https://gitlab.spack.io/spack/spack/-/jobs/11980551
=> Add new error taxonomy for missing spec list

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
This regex will catch jobs like [this one](https://gitlab.spack.io/spack/spack/-/jobs/12007967), which currently gets categorized as `other`.
=> Add new regex for `concretization_error`

k8s/production/custom/webhook-handler/deployments.yaml
Adjusts resource requests/limits for webhook Django app based on usage reported by Prometheus (https://grafana.spack.io/d/d249cc23-6930-403e-91f6-c9c30389b88d/kubernetes-deployment-cpu-and-memory-metrics?orgId=1&var-namespace=custom&var-deployment=webhook-handler-worker&var-pod=All&from=now-24h&to=now)
Underprovisioning seems to be responsible for some of the sentry errors we're seeing.
=> Re-adjust resource requests/limits for webhook handler

terraform/modules/spack/analytics_db.tf, terraform/modules/spack/gitlab_db.tf, terraform/production/.terraform.lock.hcl
This upgrades our RDS instances to the latest minor versions of Postgres/MySQL.  This has already happened for some of them across both production and staging, so this brings the terraform state up to sync and upgrades any instances that are still on an older version.
=> Upgrade RDS instances

k8s/production/custom/protected-publish/cron-jobs.yaml
4 hours limit for cron scheduled every 3 hours seems good
=> Kill protected-publish if it takes too long

terraform/modules/spack/spack_gantry.tf
Take a snapshot every 12h and keep for 5 days.
https://litestream.io/tips/#increase-snapshots-frequency-to-improve-restore-performance
=> Increase Gantry DB Backup Interval

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml
This should help alleviate some of the rate limiting problems we've recently experienced in our CI pipelines.
Note that this commit also bumps the helper_image version for the windows protected runner from v16.11.1 to v16.11.3. This patch version bump was inadvertently skipped in PR #946
=> Pull gitlab-runner-helper image from GitLab instead of Docker Hub

k8s/production/gitlab/release.yaml
This fixes an issue that occurs when performing a fresh install of the GitLab helm chart using an external cert-manager (i.e., using your own version of `cert-manager`, as we do, instead of relying on the gitlab helm chart to install and manage it).
This is the issue tracking the bug and the workaround that fixes it, which I have included in this PR.
https://gitlab.com/gitlab-org/charts/gitlab/-/issues/4907#note_1494311672
(note, this is already applied to the cluster)
Cherry picked from #954
=> Fix gitlab helm chart TLS issue

k8s/production/gitlab/release.yaml
The GitLab helm chart can take a while to start up for the first time, so this updates the HelmRelease to give it up to 15 mins to install before deciding it failed.
Cherry picked from #954
=> Extend gitlab helm release timeout

k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
This makes spinning up a cluster from scratch slightly less messy, since Flux will wait and provision things in the proper order instead of doing everything at once and causing a bunch of `CrashLoopBackoff` errors (that eventually resolve themselves).
Cherry picked out of #954
=> Add dependencies to production helm releases

k8s/production/karpenter/provisioners/base/provisioner.yaml, k8s/production/karpenter/provisioners/beefy/provisioner.yaml, k8s/production/karpenter/provisioners/gitlab/provisioner.yaml, k8s/production/karpenter/provisioners/runners/graviton/2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/testing/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml
See https://github.com/kubernetes-sigs/karpenter/issues/1009.
@jjnesbitt this was the issue that caused the issues with #937 #938 when we had to roll back that Karpenter upgrade a few months ago. I figured it out while deploying the new cluster and meant to bring it up before, but it got lost in the sea of commits in #954 :smile: 
Cherry picked from #954
=> Fix Karpenter windows scheduling issue

terraform/modules/spack_aws_k8s/versions.tf
This updates Flux to watch the `main` branch of `spack/spack-infrastructure` instead of the temporary branch from #954.
=> Point Flux at `spack/spack-infrastructure@main`

.github/workflows/terraform-drift-detection.yaml, terraform/modules/spack_aws_k8s/eks.tf, terraform/modules/spack_aws_k8s/variables.tf, terraform/modules/spack_aws_k8s/versions.tf, terraform/production/main.tf, terraform/production/variables.tf
This fixes the [Terraform drift detection job](https://github.com/spack/spack-infrastructure/blob/main/.github/workflows/terraform-drift-detection.yaml) that we stopped running before due to the TLS network timeout issues.
=> Fix kube permissions for github actions

k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml
This allows not erroring on OIDC setup for runners with service tag. Noop jobs use the service runners, but do not need access to S3 buckets. Jobs on these runners should not fail trying to find services they don't need.
If the variable `CI_OIDC_REQUIRED` is set in the job running on the runner, the value will be used. This will likely only be set on the `noop` jobs with a value of `0`.
If the variable `CI_OIDC_REQUIRED` is not set, the exit code will be `1`
ref. https://github.com/spack/spack/pull/46732
=> Allow service tagged runners to define `CI_OIDC_REQUIRED`

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/prometheus.py, k8s/production/custom/webhook-handler/deployments.yaml, terraform/modules/spack_aws_k8s/karpenter.tf
Re-enables Karpenter prometheus metrics that were inadvertently disabled in #954
=> Enable karpenter prometheus metrics

k8s/production/runners/README.md, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml
Add runner and variable documentation in README
This also fixes a problem with the previous approach where if you set `CI_OIDC_REQUIRED: 0` in your job config, then the `exit 0` here prevented any of your jobs `before_script` or `script` from running at all.
=> Change how `CI_OIDC_REQUIRED` works

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, k8s/production/custom/gh-gl-sync/cron-jobs.yaml
While setting up a new copy of the sync script for Kokkos I encountered into the following error:
fatal: --unshallow on a complete repository does not make sense
I'm not 100% sure why git decided to do a full (rather than shallow) clone for this repository, but fetching at maximum depth instead seems to solve the issue.
https://stackoverflow.com/a/46477285
=> gh-gl-sync: fetch at max depth rather than unshallow

terraform/modules/spack_aws_k8s/eks.tf
The `iam_policy_attachment` resource is for creating exclusive attachments of IAM policies to IAM roles. This prevented both staging and production from attaching their respective EBS/EFS roles to the same managed policy. See docs
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_policy_attachment
You can observe the behavior by trying to run `terraform plan` against staging on the current `main` branch. It will attempt to modify the `iam_policy_attachment` resources of the production cluster, since they are already attached.
=> Fix IAM policy attachemnts for EBS/EFS drivers

k8s/staging/spack/kustomization.yaml
@cmelone this will deploy spack-gantry to the staging cluster. I've configured it to point at the staging `spack/spack` project, but we could use another project if that makes more sense.
=> Add staging kustomization for spack-gantry

terraform/modules/spack_aws_k8s/bootstrap_s3.tf
I want to add to the existing buildcache location and run `spack buildcache
update-index` in order to merge the content. Spack needs to be able to list the
content (or use `aws s3 sync`) to run `buildcache update-index`.
This is an extension of #731 to enable `aws s3 sync` additionally to `aws s3 cp`.
=> Enable stesachs@amazon.com to run `s3 sync` on a sub-bucket

terraform/modules/spack_aws_k8s/bootstrap_s3.tf
Reverts spack/spack-infrastructure#977.
That PR introduced some invalid actions to a bucket policy, the fix is being worked on in #978. In the meantime, I'll revert that invalid PR so terraform applies cleanly again.
=> Revert "Enable stesachs@amazon.com to run `s3 sync` on a sub-bucket"

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
Example jobs (these are just from today, but I've seen these errors come up multiple times the last couple days):
https://gitlab.spack.io/spack/spack/-/jobs/13088400 
https://gitlab.spack.io/spack/spack/-/jobs/13088128
https://gitlab.spack.io/spack/spack/-/jobs/13088255 
https://gitlab.spack.io/spack/spack/-/jobs/13088333
https://gitlab.spack.io/spack/spack/-/jobs/13088178 
https://gitlab.spack.io/spack/spack/-/jobs/13088078 
https://gitlab.spack.io/spack/spack/-/jobs/13088077 
https://gitlab.spack.io/spack/spack/-/jobs/13088006 
https://gitlab.spack.io/spack/spack/-/jobs/13085121 
https://gitlab.spack.io/spack/spack/-/jobs/13084926
https://gitlab.spack.io/spack/spack/-/jobs/13084862
=> Add new regexes to error taxonomy

k8s/production/gitlab/pod-cleanup.yaml, k8s/production/gitlab/release.yaml
Update the resource requests for our GitLab pods based on the results of the following Prometheus queries:
for CPU:
```
sum(rate(container_cpu_usage_seconds_total{namespace="gitlab", pod=~"gitlab-webservice-.*"}[5m])) by (pod)
```
for memory:
```
sum by (pod) (container_memory_max_usage_bytes{namespace="gitlab", pod=~"gitlab-webservice-.*"})
```
(change pod selector to query for the other types of GitLab pods)
=> Recalibrate GitLab resource requests

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
We've been seeing this crash for a while now, where the job retry reasons field doesn't exist. This is actually expected behavior, as there is now a subset of jobs that we do not retry on failure (no-spec-to-rebuild jobs; see https://github.com/spack/spack/pull/46713/commits/e988ce058133f74066709ae8217bdb9add12190d). This went into effect about a month ago, which lines up roughly with when we first started seeing this crash.
=> Fix analytics webhook crash on non-retryable jobs

k8s/production/custom/gitlab-setting-updater/cronjobs.yaml
See https://spackpm.slack.com/archives/C02N33GM28H/p1730299174926259.
We've encountered a generated pipeline yaml that exceeded the currently set limit of 20MB (https://gitlab.spack.io/spack/spack/-/pipelines/873775). That particular yaml took 20.9MB of memory, which I was able to confirm by [patching the staging gitlab instance](https://github.com/mvandenburgh/docker-images/commit/5eee6b0d91bd92182f6009b0d7429bcbbc0fdd83) to report the memory used. (https://gitlab.staging.spack.io/mvandenburgh/spack/-/pipelines/1372)
I'm not sure what the best approach is here; I've bumped up the limit to 50MB, but technically that's a lot more than what we needed in this case. I'm not sure what the implications of a high yaml size limit are, anyone have any thoughts?
=> Increase `max_yaml_size_bytes` to 50MB

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
Prometheus still occasionally times out _inside_ the cluster. I'm not sure why yet, but I think it's good to add retries here regardless.
=> Add retries to prometheus request

terraform/modules/spack_aws_k8s/bootstrap_s3.tf
`s3:CopyObjects` and `s3:ListObjects` are not registered as IAM s3 actions. Fixes #977
=>  Enable stesachs@amazon.com to run `s3 sync` on a `pcluster/` sub-bucket

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/__init__.py, k8s/production/custom/webhook-handler/deployments.yaml
@jjnesbitt instead of trying to enumerate all the possible ways `requests` can fail transiently (such as the new `ChunkedEncodingError` [here](https://kitware-data.sentry.io/issues/6034682867/?alert_rule_id=15115735&alert_timestamp=1730415288676&alert_type=email&environment=production&notification_uuid=d144ae5f-0d71-4496-a4a0-b2787ebb8132&project=4507069616685056&referrer=alert_email)), what do you think about just retrying all `RequestException` exceptions? That's the parent class that all these exceptions inherit from.
The only downside I see is that we may end up retrying legitimate request failures, but in that case it will just retry it 3 times and propagate the exception to Sentry. That seems more reasonable to me, any thoughts?
=> Autoretry process_job for any `RequestException`

k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
Relax the constraints on our GitLab node pool, giving Karpenter more freedom to choose appropriate instance types based on our resource requests.
=> Allow Karpenter to use any amd64 for GitLab

terraform/modules/spack_gitlab/spack_gantry.tf
I think the cluster upgrade may have wiped out the change made in #955, so I'm reapplying it here.
@mvandenburgh
=> Reapply Gantry DB Backup

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
This is documented in the v0.32 upgrade guide:
https://karpenter.sh/v0.32/upgrading/v1beta1-migration/#annotations-labels-and-status-conditions
=> Replace 'do-not-evict' Karpenter annotation with 'do-not-disrupt'

k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
Runners get upgraded to 17.3.3 because that's currently their latest patch in this series.
=> Upgrade to GitLab 17.3.7

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml
Setting `cpu_limit_overwrite_max_allowed` is [required](https://docs.gitlab.com/runner/executors/kubernetes/#cpu-requests-and-limits) to enable CPU limit overwrite (ie, using `KUBERNETES_CPU_LIMIT` within build definitions).
Unlike CPU request and RAM request/limit, we should avoid setting a default CPU limit as this is for experimental purposes only.
@zackgalbreath @jjnesbitt
=> enable setting CPU limits on k8s runners

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml
Set probeTimeoutSeconds to 70 seconds, increasing it from the default value of 1 second.
This change should hopefully alleviate events of the following form:
```
Events:
Type     Reason     Age    From     Message
----     ------     ---    ----     -------
Normal   Killing    ...    kubelet  Container failed liveness probe, will be restarted
```
The ability to specify this value was added here:
https://gitlab.com/gitlab-org/charts/gitlab-runner/-/merge_requests/306
This is mentioned as a solution to the type of instability we're seeing in this upstream issue:
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/37242
For thoroughness, here's a couple other, relevant upstream MRs related to this topic:
* https://gitlab.com/gitlab-org/charts/gitlab-runner/-/merge_requests/457
* …
=> Increase probe timeout for GitLab CI runners

k8s/production/runners/public/graviton/2/release.yaml
We continue to see a lot of `pod_failed` errors for this runner. The fact that it bears the service tag is a primary difference between it and the graviton3-pub runners, which do not suffer from this same error rate.
Try removing the service tag to see if these runners start performing better.
Note that the x86-64-v2-pub runner still bears the "service" tag, and it is not used for many other types of jobs.
=> Remove service tag from graviton2-pub runners

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/error_taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
This will properly categorize jobs like the failed generate jobs from this pipeline:
https://gitlab.spack.io/spack/spack/-/pipelines/913233
```
RuntimeError: module 'spack.solver' has no attribute 'asp'
```
=> Add new `spack_error` regex to catch `module has no attribute`

k8s/production/gitlab/release.yaml
We're seeing pipelines with many jobs ([like this one](https://gitlab.spack.io/spack/spack/-/pipelines/914561)) timeout in the GitLab UI. This is happening because the UI's request to the GitLab GraphQL API is hitting its default timeout of 30 seconds. 
Note - I increased the value to 90 because the graphql call on that page took 82 (!!) seconds to load. 
Source: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/24400/diffs
=> Increase GitLab GraphQL timeout 30s=>90s

terraform/modules/spack_aws_k8s/gitlab_db.tf
Sets up the [Amazon RDS Proxy service](https://aws.amazon.com/rds/proxy/) for our gitlab RDS postgres instance. RDS Proxy is essentially an AWS-managed DB connection pooler, similar to PgBouncer. Using this will help avoid the issue we've seen lately where the webservice and/or sidekiq pods rapidly scale up and down due to load, resulting in oversaturation of DB connections and essentially DoS'ing the RDS instance.
See https://aws.amazon.com/rds/proxy/pricing/ for pricing details. For our `db.t3.xlarge` RDS instance with 4 vCPUs, using RDS Proxy would cost approximately $43.20 a month. 
0.015 (cost per hour) * 4 (vCPU count) * 24 (hours) * 30 (days) = 43.20
I've already deployed this to staging, and it works.
References used -
- [TF module …
=> Set up RDS-Proxy connection pooler for Gitlab DB

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
There's an unusually high amount of `Nominated` events for some runners (`graviton2` in particular), indicating that Karpenter is constantly rescheduling runner pods. [Dashboard](https://opensearch.spack.io/_dashboards/app/visualize#/edit/7b11c910-b8d6-11ef-96a3-41804d781b2b?type=histogram&indexPattern=59594930-ae4a-11ed-a0b4-4f356475697b&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1d,to:now))&_a=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'59594930-ae4a-11ed-a0b4-4f356475697b',key:involvedObject.namespace.keyword,negate:!f,params:(query:gitlab),type:phrase),query:(match_phrase:(involvedObject.namespace.keyword:gitlab))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'59594930-ae4a-11ed-a0b4-4f356475697b',key:involvedObject.labe …
=> Add memory requests to all GitLab runners

terraform/modules/spack_aws_k8s/eks.tf, terraform/modules/spack_aws_k8s/karpenter.tf
This re-enables Karpenter support for Windows. This will get us back to autoscaling based on load, instead of just running a couple static instances 24/7.
The issue turned out to be an IAM policy that needed to be attached to the Karpenter controller node, in order for Windows nodes to have the necessary permissions to create EC2 instance profiles. Previously, Karpenter created a static instance profile for all nodes, but starting in v1, they changed the behavior. Since we're using Karpenter for both Linux and Windows nodes, there's some complications to setting up the Terraform modules; I've expanded on the details in a code comment.
=> Re-enable Windows Karpenter nodes

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/__init__.py, analytics/analytics/job_processor/artifacts.py, analytics/analytics/job_processor/metadata.py, k8s/production/custom/webhook-handler/deployments.yaml
If a build job fails, it won't have an install_times.json.
@jjnesbitt this accounts for some, but not all, of the sentry errors complaining about missing install_times.json.
=> webhook-handler: ignore install times for failed jobs

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/build_timings.py, k8s/production/custom/webhook-handler/deployments.yaml
Since the `install_times.json` file is generated using `spack` itself, it is possible that the file is missing in a PR pipeline. This PR accounts for this case and gracefully exits when the file is missing.
We should set up alternative alerting mechanisms (like a CI test in`spack/spack` for the install_times generator, or a metabase alert that lets us know when a large amount of timing data is missing from the analytics DB) to handle this, instead of blowing up Sentry with errors when a spack PR breaks it.
=> webhook-handler: Don't crash when `install_times.json` is missing

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/build_timings.py, k8s/production/custom/webhook-handler/deployments.yaml
This should fix all the `KeyError` errors we've been seeing in sentry.
This was being caused by install time entries that didn't exist in the spec json. This seems to mainly occur with bootstrapped packages.
=> Ignore all extra cache=False install times

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/utils.py, k8s/production/custom/webhook-handler/deployments.yaml
GitLab itself won't timeout until after 60 seconds https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/bulk_imports/clients/graphql.rb#L7, and we've seen cases where fetching a job trace takes more than 15 seconds. So, I've bumped the timeout for the GitLab Python client to 30 seconds to account for this; we can always increase it further if needed, but I think this should be a good start while avoiding potentially introducing head-of-line blocking to the celery queue.
=> webhook-handler: increase gitlab API timeout

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/dimensions.py, k8s/production/custom/webhook-handler/deployments.yaml
The 	`get_or_create` calls used to create dimensional rows allowed for `IntegrityError` to be raised. This PR updates those calls to only query by the primary key, to prevent such an occurrence.
=> Prevent violated unique constraints on dimension row creation

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/build_timings.py, k8s/production/custom/webhook-handler/deployments.yaml
Install timers that are not a part of the built spec (the spec from the package being built in the job) can exist in the `install_times.json`. To prevent this from causing errors in our install times processing, we ignore all of these.
=> Ignore install timers that aren't from the built spec

.github/workflows/custom_docker_builds.yml, images/protected-publish/publish.py, k8s/production/custom/protected-publish/cron-jobs.yaml
When moving the `protected-publish` job from spack gitlab pipelines to a dedicated cron job, I neglected to take care of publishing the signing key to the root mirror.  This PR resolves that issue.
I tested this change by removing a spec from the `s3://spack-binaries/v0.23.0` mirror, then building the imgae locally, and running the container to publish the `v0.23.0` ref.  After which, I could successfully install keys from that mirror:
```
$ git clone https://github.com/spack/spack.git
$ cd spack
$ git checkout v0.23.0
$ spack mirror add binaries s3://spack-binaries/v0.23.0
$ spack buildcache keys --install
==> Fetching s3://spack-binaries/v0.23.0/build_cache/_pgp/spack-public-binary-key.pub
```
=> Include public signing key when publishing stacks

.github/workflows/custom_docker_builds.yml, images/retry-trigger-jobs/Dockerfile, images/retry-trigger-jobs/README.md, images/retry-trigger-jobs/requirements.txt, images/retry-trigger-jobs/retry_trigger_jobs.py, k8s/production/custom/retry-trigger-jobs/cron-jobs.yaml
=> New cron job to automatically retry failed trigger jobs

terraform/modules/spack_aws_k8s/eks.tf, terraform/modules/spack_aws_k8s/karpenter.tf
Updates the kubernetes version of our EKS cluster to the latest version (1.31). Nothing in this upgrade requires any changes to our infrastructure, see [upgrade docs](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions-standard.html#kubernetes-1.31).
This PR also upgrades Karpenter's patch version (1.0.0 => 1.0.5). This is required because 1.0.5 is the minimum supported version for k8s v1.31 (see https://karpenter.sh/docs/upgrading/compatibility/). This is only a patch release, so no breaking changes are introduced. There _is_ a minor upgrade for Karpenter available (1.1), but I figured we can do that in a follow up to avoid making too many unrelated changes here.
I've applied this to the staging cluster, and everything appears to be working as intended. Example gitlab …
=> Upgrade EKS to v1.31

.github/workflows/custom_docker_builds.yml
Reverts spack/spack-infrastructure#1045
This update broke image pushing to GHCR. I'm not sure what's going on, the changelog doesn't indicate anything that would cause a breakage like this. Just reverting this for now :shrug:
=> Revert "[gh-actions](deps): Bump docker/build-push-action from 6.12.0 to 6.13.0"

.github/workflows/custom_docker_builds.yml
The GitHub docs say to include these fields in order to push to the GHCR - https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-github-packages. We've never set them before and pushing has worked just fine until now, but there's at least one instance of this randomly fixing the issue for others (https://github.com/docker/build-push-action/issues/687#issuecomment-1651816012)
=> Set `permissions` for pushing to GHCR

k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml
The helper image for v17.8.1 doesn't seem to be available in the gitlab container registry. Despite being listed here
https://gitlab.com/gitlab-org/gitlab-runner/container_registry/1472754?orderBy=NAME&sort=desc&search[]=x86_64-v1&search[]=servercore21H2, running a `docker pull` on it fails.
I've downgraded it for now to 17.7.1, as all windows CI jobs are currently failing with a `pod failed` error due to this.
=> Downgrade windows runners to v17.7.1

terraform/modules/spack_aws_k8s/analytics_db.tf, terraform/modules/spack_aws_k8s/cdash_db.tf
Similar to #1060. We don't have any pressing issues with the performance of `gp2` on these instances, but `gp3` is cheaper in addition to more performant, so there's only upsides to doing this.
=> Update analytics, CDash RDS instances to gp3

.github/workflows/custom_docker_builds.yml, images/cache-indexer/cache_indexer.py, k8s/production/custom/cache-indexer/cron-jobs.yaml
The cache indexer runs nightly looking for buildcache indices in the `spack-binaries` bucket.  Once [spack/spack#48713](https://github.com/spack/spack/pull/48713) is merged, spack will cease putting buildcaches under the `build_cache` directory/prefix of a mirror, and instead it will begin putting them under `v3/specs`. At that point the cache indexer will have until the end of the day to update to do the same.
This PR contains a small refactor which we can merge now, to make that transition easier so only a tiny cache_indexer change is required once the spack PR is merged.
=> cache_indexer: prepare for change to content-addressable

images/protected-publish/develop_stacks.txt
This is just to record the stacks we're migrating, so it should not require any image version bumps.
=> migration: update develop stack list

k8s/production/gitlab/release.yaml
Addresses https://nvd.nist.gov/vuln/detail/CVE-2025-1257
=> Upgrade to GitLab 17.9.2

terraform/modules/spack_aws_k8s/karpenter.tf
The name of the relevant value appears to be settings.interruptionQueue, not settings.interruptionQueueName
https://github.com/aws/karpenter-provider-aws/blob/v1.1.0/charts/karpenter/values.yaml#L173
https://karpenter.sh/docs/upgrading/upgrade-guide/#upgrading-to-0320
=> Enable interruption handling for Karpenter

.github/workflows/custom_docker_builds.yml, k8s/production/runners/signing/release.yaml
Instead of using the `latest` tag when we push the notary image and use it in the signing runner helm release, prefer numbered tags.  The goal here is to allow spack develop to keep using a known working version, while allowing us to test the next version elsewhere.
=> notary: build/use numbered tags instead of 'latest'

.github/workflows/custom_docker_builds.yml, images/notary/sign.sh
After content-addressable tarballs is merged, clearsigning will be performed on spec manifest files, without changing the name of the file. This change keeps the original file name when re-signing, and to prevent issues with gpg overwriting files, it puts re-signed files into a different directory from the original files.
This can be merged before the content-addressable tarballs spack [PR](https://github.com/spack/spack/pull/48713).
=> notary: Use separate input and output directories

k8s/production/runners/signing/release.yaml
The goal of this PR is to allow us to specify the image used by the spack signing job by it's computed sha.
=> signing: allow specifying image by sha

images/notary/sign.sh
Now that we store specs in subdirectories named after the package, we need to preserve that structure when moving the files from the input directory to the verified directory, and again when moving them from the verified directory to the output directory.
I think this should actually preserve whatever structure we find inside `/tmp/input/` all the way through to the files we write to `/tmp/output/`, so if we decide to reorganize things again, we can hopefully avoid yet another change to this signing script.
=> sign.sh: Preserve package name subdirectories when signing

k8s/production/custom/gitlab-gitaly-bundle-refresher/cronjobs.yaml, k8s/production/custom/gitlab-gitaly-bundle-refresher/serviceaccounts.yaml, k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/graviton/4/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/graviton/4/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml, terraform/modules/spack_aws_k8s/gitlab_object_stores.tf
This enables the "bundle URI" feature for Gitaly (gitlab's internal remote git server). Bundle URIs are a part of the `git` protocol and allow parts of the git repo to be cached in another place, (S3 in our case). `git clone` is essentially be redirected to S3 when there are cache hits, which lowers the overall load on gitaly itself.
The gitlab docs on this are not great and do not specify how to configure the gitlab helm chart to use it, but I was able to figure it out by looking at the gitaly helm chart internals (https://gitlab.com/gitlab-org/charts/gitlab/-/commit/556a5b1e3a6f6692dbc4c829fae5b4558d0f4ccf). It's deployed on staging and works.
Note: this requires a gitlab upgrade since the commit referenced above was released for the first time in gitlab 17.11.0.
`git` docs - …
=> Enable Gitaly Bundle URIs

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/artifacts.py, analytics/analytics/job_processor/build_timings.py, k8s/production/custom/webhook-handler/deployments.yaml
Fixes an issue where the webhook handler would crash if processing jobs from https://github.com/spack/spack/pull/49547.
Previously we simply hardcoded paths like `jobs_scratch_dir/reproduction/cloud-ci-pipeline.yml`. Since this occasionally changes, searching through the artifacts file list fixes the problem.
=> Search through artifacts zip for files of interest

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/artifacts.py, k8s/production/custom/webhook-handler/deployments.yaml
Fixes the buggy implementation from #1095. Tested successfully against several jobs in gitlab.
=> Fix faulty logic in `find_job_artifacts_file`

.github/workflows/custom_docker_builds.yml, images/protected-publish/pkg/common.py, images/protected-publish/pkg/publish.py, k8s/production/custom/protected-publish/cron-jobs.yaml
Updates the v3 version of protected publish to correctly look for manifests, generating the meta and archive urls from those.
I tested this by publishing a single test stack (build_systems) to the root under both v2 and v3 layouts.  We should be able to merge it now, and publishing v2 stacks to the root will continue to work.  Once the content-addressable tarballs PR is merged to spack `develop`, we will need a tiny PR to the cron job arguments to swtich from `--version 2` to `--version 3`.
=> Fix protected publish for v3 layout buildcaches

.github/workflows/custom_docker_builds.yml, images/cache-indexer/cache_indexer.py, k8s/production/custom/cache-indexer/cron-jobs.yaml
Iterates bucket looking for index manifests, rather than the indices themselves.  Each manifest is retrieved in order to get the content address of the index, then the url to the index content blob is stored under the "url" key.
Support for v3 is still hidden behind a comment, so one more PR to switch that commenting is required to actualy change from v2 to v3.
=> cache_indexer: Add support for newest spack buildcache layout v3

.github/workflows/custom_docker_builds.yml, images/protected-publish/TESTING.txt, images/protected-publish/migrate_job.yaml, images/protected-publish/pkg/common.py, images/protected-publish/pkg/migrate.py, k8s/production/custom/protected-publish/cron-jobs.yaml
Update migration logic to latest layout structure:
- For all specs:
* Download v2 spec, compress it, and compute checksum
* Push compressed spec as a blob
* Create and push manifest for buildcache entry (including archive and spec file)
- For all public keys:
* Download key, compute checksum and size
* Push uncompressed key as blob
* Create and push key manifest
Buildcache index and public key index are still handled by `spack buildcache update-index --keys <mirror-url>` after completing the steps above.  The `update-index` is currently using my branch, but can be updated to use mainline spack `develop` after the content-addressable tarballs [PR](https://github.com/spack/spack/pull/48713) is merged.
=> Fix migration to create most recent layout

.github/workflows/custom_docker_builds.yml, images/cache-indexer/cache_indexer.py, images/protected-publish/migrate_job.yaml, images/protected-publish/pkg/migrate.py, k8s/production/custom/cache-indexer/cron-jobs.yaml, k8s/production/custom/protected-publish/cron-jobs.yaml
This PR updates the way some things work to how they'll be after spack switches to content-addressable tarballs:
- Update the version of spack used by the migration logic to use the `develop` branch of spack from the mainline repo, in case any further migration is needed after merging the spack PR
- Update the cache-indexer so it looks in the correct location for buildcache indices
- Change the layout version to 3 on the cli of the publish cron job
This is a draft, as it should not be merged until the content-addressable tarballs [PR](https://github.com/spack/spack/pull/48713) has been merged into spack `develop`.
=> Post content addressable tarballs

.github/workflows/custom_docker_builds.yml, images/protected-publish/migrate_job.yaml, images/protected-publish/pkg/publish.py, k8s/production/custom/protected-publish/cron-jobs.yaml
I must have failed to update these media types after the most recent change request to the spack content-addressable tarballs PR, as when I was testing #1099, my branch of spack was still using `buildcache_spec.v3` and `install.v1`.
This updates those media types to match value used by spack (and the migrate job).
=> Update media types used in protected publish

.github/workflows/custom_docker_builds.yml, images/protected-publish/Dockerfile, images/protected-publish/migrate_job.yaml, k8s/production/custom/protected-publish/cron-jobs.yaml
We stopped getting output from the protected-publish cron job when moving from `0.0.6` to `0.0.7`. This PR is an attempt to get it back.
=> protected-publish: Do not buffer python output

terraform/modules/spack_gitlab/delete_stale_branches.tf, terraform/modules/spack_gitlab/gitlab.tf, terraform/modules/spack_gitlab/modules/spackbot_personal_access_token/main.tf, terraform/modules/spack_gitlab/modules/spackbot_personal_access_token/outputs.tf, terraform/modules/spack_gitlab/modules/spackbot_personal_access_token/variables.tf, terraform/modules/spack_gitlab/modules/spackbot_personal_access_token/versions.tf, terraform/modules/spack_gitlab/spack_gantry.tf, terraform/modules/spack_gitlab/spackbot_secrets.tf, terraform/modules/spack_gitlab/webhooks.tf
This PR does two things:
1) Refactors gitlab personal access tokens into a reusable Terraform module
2) Increases the time we will get warned about expiring tokens from 1 day before the expiration date to 1 month.
Currently we use the GitLab Terraform provider's [`gitlab_personal_access_token`](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs/resources/personal_access_token) resource to manage the access tokens we need to create and store in k8s secrets for use by our various cron jobs and other services to interact with the GitLab API. I set up some [Terraform `precondition` rules](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#preconditions-and-postconditions) to fail TF plans if any token is set to expire in the next day.
This …
=> Refactor management of gitlab access tokens

.github/workflows/custom_docker_builds.yml, images/protected-publish/migrate_job.yaml, images/protected-publish/pkg/common.py, images/protected-publish/pkg/publish.py, k8s/production/custom/protected-publish/cron-jobs.yaml
This PR does two things to speed up protected publish:
1. Use `aws s3 sync ...` to download the manifests, instead of the current approach of `s3_client.download_fileobj()` for each one using multithreading
2. When copying the manifest, metadata, and archive for a spec, create only one s3 session rather than three
=> protected-publish: Speed up publishing specs to the root

.github/workflows/custom_docker_builds.yml, .github/workflows/spack_ci_bridge.yml, images/gh-gl-sync/SpackCIBridge.py, k8s/production/custom/gh-gl-sync-packages/cron-jobs.yaml, k8s/production/custom/gh-gl-sync/cron-jobs.yaml, k8s/production/custom/kokkos-sync/cron-jobs.yaml
This is based off of the updates to sync for the new `spack-packages` repo. The bridge test hasn't been running since the Ubuntu 20 image was dropped in GHA.
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
```
=> Run bridge tests

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, k8s/production/custom/gh-gl-sync-packages/cron-jobs.yaml, k8s/production/custom/gh-gl-sync/cron-jobs.yaml, k8s/production/custom/kokkos-sync/cron-jobs.yaml
Create a new sync script cron for the packages repo. Reuse the robot secrets from the existing `gh-gl-sync` cron.
=> Add gh-gl-sync cron for spack-packages

k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/graviton/4/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/graviton/4/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
This will enable the `FF_WAIT_FOR_POD_TO_BE_REACHABLE` feature flag on all of our AWS/k8s-based GitLab runners. This feature flag makes it so a runner executor pod is only "Ready" in k8s (and thus can accept new jobs) when the underlying node has its TLS certificates all ready.
This helps avoid an issue where a runner executor pod gets scheduled on a brand new node that has no certs yet, resulting in new jobs failing with errors like these that @tgamblin saw over the weekend -
- https://gitlab.spack.io/spack/spack/-/jobs/16676859
- https://gitlab.spack.io/spack/spack/-/jobs/16676867
- https://gitlab.spack.io/spack/spack/-/jobs/16676872
See https://docs.gitlab.com/runner/configuration/feature-flags/ (ctrl-F for `FF_WAIT_FOR_POD_TO_BE_REACHABLE`)
As part of this PR, I've also moved the …
=> Enable `FF_WAIT_FOR_POD_TO_BE_REACHABLE` on all k8s runners

k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/graviton/4/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/graviton/4/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
Reverts spack/spack-infrastructure#1122
We've seen a large increase in runner system failures after enabling this feature flag. Reverting until we figure out more details.
=> Revert "Enable `FF_WAIT_FOR_POD_TO_BE_REACHABLE` on all k8s runners"

terraform/modules/spack_aws_k8s/karpenter.tf
A common system error in Spack CI is this `image pull failed: pull QPS exceeded`.
GitHub container registry claims to have no rate limits for pulling images, but it seems they do have an unpublished queries-per-second (QPS) of 1. I was able to replicate the issue with [artificially generated pipelines in staging](https://gitlab.staging.spack.io/mvandenburgh/testci/-/pipelines/1687) and played around with lowering `--registry-qps`[^docs]  (a kubelet argument that lets kubernetes know how many images it can pull in parallel; Amazon Linux EKS-optimized AMI defaults to `5`), and still encountered that QPS limit error even going down to just `2`.
We can disable parallel image pulling by setting the `--serialize-image-pulls`[^docs] kubelet argument to true.
(actually, kubelet's default behavior …
=> Enable `--serialize-image-pulls` for Karpenter linux nodes

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/__init__.py, analytics/analytics/job_processor/dimensions.py, k8s/production/custom/webhook-handler/deployments.yaml
Follow on to #1050 
I moved the `job_type` field from the `gitlab_job_data_dimension` table to the `spack_job_data_dimension` table, but missed a couple of spots where `job_type` was still being used with `gitlab_job_data_dimension` table.
=> Fix lingering job_type field in gitlab job data dimension

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/utils.py, k8s/production/custom/webhook-handler/deployments.yaml
`sentry_sdk` is used in this module but is not imported. 
We should probably start using `flake8` at least to catch things like this. Or ideally, just replace the entire linting toolchain with `ruff`.
=> Add missing python import

k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/graviton/4/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/sealed-secrets.yaml, k8s/production/runners/signing/release.yaml, k8s/production/runners/signing/sealed-secrets.yaml
This applies the same change as #1152 to protected and signing runners. This also removes the `spack-project-runner-registration-token` and `spack-signing-runner-secret` secrets, as they are no longer used (and contained no unique information anyway).
=> Make protected and signing runners spack group runners

terraform/modules/spack_aws_k8s/iam_service_accounts.tf
This service account is referenced by the spackbot-dev deployment, but isn't defined anywhere, resulting in the `spackbotdev-workers` deployment from failing to start.
@kwryankrattiger so it looks like spackbot-dev was failing to start its workers long before #1159.
=> Add missing svc account for spackbotdev

k8s/production/karpenter/provisioners/base/provisioner.yaml, k8s/production/karpenter/provisioners/beefy/provisioner.yaml, k8s/production/karpenter/provisioners/gitlab/provisioner.yaml, k8s/production/karpenter/provisioners/runners/graviton/3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/graviton/4/provisioners.yaml, k8s/production/karpenter/provisioners/runners/testing/provisioners.yaml, k8s/production/karpenter/provisioners/runners/windows/x86_64/v2/provisioner.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v2/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v3/provisioners.yaml, k8s/production/karpenter/provisioners/runners/x86_64/v4/provisioners.yaml, terraform/modules/spack_aws_k8s/karpenter.tf
The v1beta1 API is deprecated, and removed in Karpenter 1.1. See https://karpenter.sh/v1.0/upgrading/v1-migration/#before-upgrading-to-v110 for the required changes.
=> Update Karpenter manifests to apiVersion v1

k8s/production/ingress-nginx/release.yaml, k8s/production/metabase/metabase-deployment.yaml, k8s/production/prometheus/release.yaml
Note this PR also updates the timeout for the `kube-prometheus-stack` Helm chart; we frequently see that time out and take longer than 10 minutes (the default timeout), requiring a manual restart.
=> Service Upgrade 9/2/25

scripts/gitlab_runner_pre_build/pre_build.py
This is required in order to ensure no collisions between PR started from different repositories.
PR change [here](https://github.com/spack/spack-packages/pull/342/files#diff-f8188dc893dfb8c4140ed2ce9cd2b927e97e88f331bf4221c5dd3d95caafa671)
Error in CI [here](https://gitlab.spack.io/spack/spack/-/jobs/18009189#L1249)
=> Add project name namespace to PR cache

analytics/Dockerfile, analytics/dev/django.Dockerfile
The image is failing to build because it's attempting to install `python3-distutils`, which is deprecated in favor of `setuptools`. As far as I can tell, we don't actually need either package, so I've simply removed it.
=> Fix analytics docker image build

.github/workflows/custom_docker_builds.yml, images/runner-node-certificate-controller/main.py, k8s/production/custom/runner-node-certificate-controller/cron-jobs.yaml, k8s/production/custom/runner-node-certificate-controller/service-accounts.yaml
It seems I manually edited some of the service account permissions when I was testing this in staging, and neglected to commit them to the service-accounts.yaml. This fixes that, plus removes all the exception handling that was suppressing these errors from the log output and erroneously claiming no nodes were ready. Instead, any errors will trigger a sentry alert
=> Fix CSR script

.gitignore
Adds common IDE config files to the `.gitignore`.
=> Ignore VSCode and PyCharm config files
