README.md, kubernetes/spack/cdash-spack-io/db/pv.yaml, kubernetes/spack/cdash-spack-io/db/pvc.yaml, kubernetes/spack/gitlab-spack-io/cache/pv.yaml, kubernetes/spack/gitlab-spack-io/cache/pvc.yaml, kubernetes/spack/gitlab-spack-io/db/pv.yaml, kubernetes/spack/gitlab-spack-io/db/pvc.yaml, kubernetes/spack/gitlab-spack-io/web/pv.yaml, kubernetes/spack/gitlab-spack-io/web/pvc.yaml, kubernetes/spack/staging-spack-io/cdash/db/deployments.yaml, kubernetes/spack/staging-spack-io/cdash/db/pv.yaml, kubernetes/spack/staging-spack-io/cdash/db/pvc.yaml, kubernetes/spack/staging-spack-io/cdash/db/services.yaml, kubernetes/spack/staging-spack-io/cdash/web/certificates.yaml, kubernetes/spack/staging-spack-io/cdash/web/deployments.yaml, kubernetes/spack/staging-spack-io/cdash/web/ingress.yaml, kubernetes/spack/staging-spack-io/cdash/web/services.yaml
Separate "staging" instance of CDash that we can use to demo proposed changes
Also convert our PersistentVolumeClaims from dynamic to static provisioning.
=> Add YAML resources for cdash.staging.spack.io

kubernetes/spack/gitlab-spack-io/runner/daemonsets.yaml, kubernetes/spack/gitlab-spack-io/runner/deployments.yaml
=> Convert gitlab-runners to a daemonset

gitlab-docker/README.md
Make sure the workflow still works as documented.
=> Make a couple changes to the documentation

kubernetes/spack/gitlab-spack-io/web/deployment.yaml
* Enable Prometheus / Grafana monitoring for GitLab
* Move GitLab to a bigger instance (r5.xlarge)
=> Enable monitoring on GitLab

kubernetes/spack/cdash-spack-io/db/pv.yaml, kubernetes/spack/cdash-spack-io/db/pvc.yaml, kubernetes/spack/gitlab-spack-io/db/pv.yaml, kubernetes/spack/gitlab-spack-io/db/pvc.yaml, scripts/migrate-data.sh
Also adds a script to help partially automate copying data over from one EBS volume to another.
=> increase DB storage/add data migration script

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py, kubernetes/spack/internal-spack-io/gh-gl-sync/cron-jobs.yaml
=> Sync protected branches

gh-gl-sync/SpackCIBridge.py
Make the status post back to GitHub optional, so we can run multiple sync cron jobs against the same GitHub repo.
=> Make the GitHub status post optional

.github/workflows/spack_ci_bridge_docker.yml, k8s/custom/gitlab-api-scrape/cron-jobs.yaml, k8s/custom/gitlab-api-scrape/service-accounts.yaml, scripts/gitlab_api/gitlab_api.py
Migrate from IAM credentials to IAM role + kube serviceAccount.
Also change the S3 we write logs too, and version bump the relevant
Docker image.
=> Use Kubernetes service account for gitlab-api-scrape

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Also, don't post canceled status to GitHub
=> Let develop pipelines run to completion

kubernetes/spack/spackbot-spack-io/web/certificates.yaml, kubernetes/spack/spackbot-spack-io/web/deployments.yaml, kubernetes/spack/spackbot-spack-io/web/ingress.yaml, kubernetes/spack/spackbot-spack-io/web/services.yaml
This adds the Kubernetes files for spackbot.spack.io, a bot that manages
notifications to package maintainers and labels for Spack PRs.
=> Add spackbot.spack.io

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Fix this error:
(forced update) shallow update not allowed
=> shallow fetching from github was a bad idea

k8s/runners/huge-pub/release.yaml, k8s/runners/large-pub/release.yaml, k8s/runners/medium-pub/release.yaml, k8s/runners/small-pub/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-pub/release.yaml, scripts/eks-node-group-with-key.yaml, scripts/eks-node-group.yaml
Fix is implemented in a change to the cloud formation templates that we use to provision the node pools.
TODO List:
=> Fix an issue preventing node pools from scaling from 0 instances.

k8s/prometheus/release.yaml, k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/small-arm-pub/release.yaml, k8s/runners/small-x86-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
Last step in fixing the autoscaling issue.
Also updates all runners so that we have a complete offering of both x86 and arm runners.
=> fix/update runners & fix prometheus release

k8s/spack/www-spack-io/deployments.yaml
=> Change source of spack.io container to ghcr

k8s/spack/spackbot-spack-io/deployments.yaml
Test the temporary container, in production of course!
=> Depoly a temporary spackbot image built from e3405654bb (#125)

.github/workflows/spack_ci_bridge_docker.yml, gh-gl-sync/SpackCIBridge.py, gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Don't backlog PRs we weren't going to push anyway.
=> Bring backlog fix to production

.github/workflows/custom_docker_builds.yml, images/gitlab-sidekiq/Dockerfile, images/gitlab-task-runner/Dockerfile, images/gitlab-webservice/Dockerfile
I might have to iterate on these changes if they don't build straight away.
=> update custom gitlab images to v14.4.1

.github/workflows/custom_docker_builds.yml, images/gitops/entrypoint.py, k8s/gitops/deployments.yaml
=> fix missing import in gitops controller

k8s/gitops/deployments.yaml
=> set gitops deployment strategy to Recreate

k8s/ingress-nginx/release.yaml
@opadron PTAL and just merge if it looks good to you (PTALAJMIILGTY?)
=> Enable ingress metrics

k8s/prometheus/alertmanagerconfig.yaml, k8s/prometheus/release.yaml, k8s/prometheus/secrets.yaml, scripts/dummyalert.sh
=> Add Slack notification to Prometheus Alert Manager

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Who put that comma there anyway?
=> Fix status posted for backlogged PRs (for real this time)

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
Fixes an issue where runners were not scaling to their correct max size.
=> fix gitlab runner concurrent settings

k8s/runners/huge-arm-pub/release.yaml, k8s/runners/huge-x86-pub/release.yaml, k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-x86-pub/release.yaml, k8s/runners/large-x86-tmp-pub/release.yaml, k8s/runners/medium-arm-pub/release.yaml, k8s/runners/medium-x86-pub/release.yaml, k8s/runners/staging/release.yaml, k8s/runners/xlarge-arm-pub/release.yaml, k8s/runners/xlarge-x86-pub/release.yaml
See here for evidence:
https://docs.gitlab.com/runner/executors/kubernetes.html#other-configtoml-settings
=> Fix poll_timeout for AWS GitLab runners

k8s/prometheus/release.yaml
=> Temporary Fix to handle metric label propagation

k8s/spack/spackbot-spack-io/deployments.yaml
Reverts spack/spack-infrastructure#173
=> Revert "Support spackbot fixing style in worker process"

.github/workflows/custom_docker_builds.yml, images/gitlab-stuckpods/Dockerfile, images/gitlab-stuckpods/README.md, images/gitlab-stuckpods/entrypoint.sh, k8s/custom/gitlab-stuckpods/deployment.yaml, k8s/custom/gitlab-stuckpods/service-accounts.yaml
The substantive implementation is complete, tested and ready for review @opadron @zackgalbreath 
Still need too:
+ [x] add github job to build image 
+ [x] change image used in deployment
+ [x] briefly document
=> Add image and deployment for stuckpod mitigation

k8s/runners/large-arm-pub/release.yaml, k8s/runners/large-arm-testing-pub/release.yaml
As requested from #aws-hack-week
Don't merge until @josephsnyder creates the new arm pools.
=> hotfix: add arm runners (production & testing)

.github/workflows/custom_docker_builds.yml, images/notary/Dockerfile, images/notary/sign.sh, k8s/runners/signing/release.yaml, k8s/runners/signing/secrets.yaml, k8s/runners/signing/serviceaccount.yaml
Add infrastructure to manage signing packages
=> [WIP] Signing infrastructure

k8s/gitlab/release.yaml
Relevant configuration docs:
https://github.com/helm/charts/tree/aaaf98b5d25c26cc2d483925f7256f2ce06be080/stable/minio#configuration
=> Distributed MinIO for GitLab

images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py
Reverts spack/spack-infrastructure#248
=> Revert "Stop prefixing branches with 'github/'"

.github/workflows/custom_docker_builds.yml
Fixes the id and names in the github workflows for building images so that they use consistent naming.
=> fix naming in image-building workflows

.github/workflows/custom_docker_builds.yml, images/gh-gl-sync/SpackCIBridge.py, images/gh-gl-sync/test_SpackCIBridge.py, k8s/custom/gh-gl-sync/cron-jobs.yaml
Reverts spack/spack-infrastructure#254
🙃
=> Revert "Revert "Stop prefixing branches with 'github/'""

k8s/spack/spackbot-spack-io/deployments.yaml
Hotfix: fix spackbot secret names
=> Fix spackbot secret names

k8s/logging/fluent-bit.yaml
Installs [Fluent Bit](https://fluentbit.io/) into the cluster as a `DaemonSet`.
=> Install fluent bit

k8s/gitlab/release.yaml, k8s/gitlab/staging/release.yaml
Another attempt following #283. https://fluxcd.io/legacy/helm-operator/helmrelease-guide/values/#secrets
=> Fix format of HelmRelease secret values

k8s/gitlab/release.yaml, k8s/gitlab/secrets.yaml, k8s/gitlab/staging/release.yaml
Another attempt at getting https://fluxcd.io/legacy/helm-operator/helmrelease-guide/values/#secrets to work.
=> Specify RDS hostname as a secret

scripts/aws-auth.yaml
Whenever modifying this ConfigMap in the cluster, please try to remember to also update this file by running:
`kubectl -n kube-system get cm aws-auth -o jsonpath='{.data.mapRoles}' > aws-auth.yaml`
=> Add a copy of aws-auth ConfigMap to version control

k8s/spack/spackbot-spack-io/deployments.yaml, k8s/spack/spackbot-spack-io/service-accounts.yaml, k8s/spack/spackbotdev-spack-io/deployments.yaml, k8s/spack/spackbotdev-spack-io/service-accounts.yaml
Provide spackbot with permission to delete from the PR binaries mirrors
=> Make sure spackbots can delete from pr mirrors

images/notary/sign.sh, k8s/runners/signing/secrets.yaml
Tested key import works with the updated k8s secret. @scottwittenburg PTAL
=> Add uo_intermediate_ci_public_key to signing job

k8s/prometheus/custom/alerts.yaml
Already applied this to the cluster.
=> Disable stuck pods slack alert

images/opensearch-index-build-logs/requirements.txt, k8s/custom/gitlab-error-processor/deployments.yaml
Fixes some more issues have been plaguing some of the pods in the `custom` namespace, which surfaced after I applied the previous fixes from my PRs yesterday
=> Misc fixes to jobs in `custom` namespace

terraform/modules/spack/eks.tf
Reverts spack/spack-infrastructure#391
=> Revert "Remove SG rule allowing ingress on all ports"

terraform/modules/spack/variables.tf, terraform/modules/spack/vpc.tf, terraform/production/main.tf, terraform/staging/main.tf
Resolves the NAT gateway issue from the LLNL email.
=> Always use multiple NAT gateways for VPC

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
=> Update taxonomy grafana dashboard to sort classifications by doc count

k8s/runners/protected/graviton/2/release.yaml, k8s/runners/protected/graviton/3/release.yaml, k8s/runners/protected/x86_64/v2/release.yaml, k8s/runners/protected/x86_64/v3/release.yaml, k8s/runners/protected/x86_64/v4/release.yaml, k8s/runners/public/graviton/2/release.yaml, k8s/runners/public/graviton/3/release.yaml, k8s/runners/public/x86_64/v2/release.yaml, k8s/runners/public/x86_64/v3/release.yaml, k8s/runners/public/x86_64/v4/release.yaml, k8s/runners/signing/release.yaml, k8s/runners/testing/graviton/2/release.yaml, k8s/runners/testing/x86_64/v3/release.yaml
This will prevent runner pods from being evicted via consolidation, among other things. [Here](https://karpenter.sh/preview/concepts/deprovisioning/#disabling-deprovisioning) are the relevant docs.
=> Do not evict runner pods

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml
=> Add gitlab `build_failure_reason` to dashboard

images/upload-gitlab-failure-logs/taxonomy.yaml
Add some classifications for "other" errors from past week
=> Error Taxonomy: Add classification for network errors

k8s/prometheus/custom/gitlab-ci-failures-dashboard.yaml, k8s/prometheus/custom/gitlab-pipeline-dashboard.yaml
This will allow us to more easily link them from the front page
=> Add 'production' tag to useful dashboards

k8s/prometheus/custom/gitlab-pipeline-dashboard.yaml
=> change the right tag

k8s/runners/protected/graviton/2/release.yaml, k8s/runners/protected/graviton/3/release.yaml, k8s/runners/protected/x86_64/v2/release.yaml, k8s/runners/protected/x86_64/v3/release.yaml, k8s/runners/protected/x86_64/v4/release.yaml, k8s/runners/public/graviton/2/release.yaml, k8s/runners/public/graviton/3/release.yaml, k8s/runners/public/x86_64/v2/release.yaml, k8s/runners/public/x86_64/v3/release.yaml, k8s/runners/public/x86_64/v4/release.yaml, k8s/runners/signing/release.yaml, k8s/runners/testing/graviton/2/release.yaml, k8s/runners/testing/x86_64/v3/release.yaml
=> Add required `weight` field to pod affinity

terraform/staging/main.tf
Same changes as #456 but for staging
=> Update eks get-token invocation for staging terraform

images/upload-gitlab-failure-logs/taxonomy.yaml
Update/fix the following existing categories:
- pod_failed: https://gitlab.spack.io/spack/spack/-/jobs/6526439
- pod_timeout: https://gitlab.spack.io/spack/spack/-/jobs/6500234
Add regexes for new kinds of errors encountered in the last week:
- unallowed_image: https://gitlab.spack.io/spack/spack/-/jobs/6523533
- deprecated_stack_bug: https://gitlab.spack.io/spack/spack/-/jobs/6513933
- aborted_terminated: https://gitlab.spack.io/spack/spack/-/jobs/6505877
- gpg_fail_open_files: https://gitlab.spack.io/spack/spack/-/jobs/6490439
- gpg_no_valid_ids: https://gitlab.spack.io/spack/spack/-/jobs/6490429
- nvidia_detection_error: https://gitlab.spack.io/spack/spack/-/jobs/6478929
- pod_invalid: https://gitlab.spack.io/spack/spack/-/jobs/6478826
- bootstrap_patchelf_failure: …
=> Error taxonomy: update a couple existing and add 8 new

k8s/production/runners/signing/serviceaccount.yaml, terraform/modules/spack/eks.tf
Depends on #478, so please only look at the last commit when evaluating changes
=> Encode Notary IAM role/policy and ServiceAccount into Terraform

k8s/staging/runners/kustomization.yaml
This file was removed in #485.
=> Remove signing runner service account from staging

k8s/staging/karpenter/kustomization.yaml
Forgot to update these after changing the region of the staging cluster in #502
=> Update Karpenter AZs for new staging cluster region

k8s/production/runners/protected/pcluster/graviton/3/release.yaml
PCluster AMI does not have the keys, prefer the secrets
=> Remove host path mounted keys

k8s/production/prometheus/oauth2-proxy.yaml, k8s/staging/prometheus/kustomization.yaml
- Adds @alecbcs
- Fixes the case sensitivity issue with @AlmightyYakob (we should file bug upstream in oauth2-proxy for this)
=> Update oauth2-proxy github access

k8s/production/prometheus/oauth2-proxy.yaml, k8s/staging/prometheus/kustomization.yaml
=> Add cmelone to prometheus users

k8s/staging/gitlab/kustomization.yaml
=> Remove log cleaner from kustomization

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml
This is the rewritten runner configuration that should run on any machine with python3.
=> Add dependency-free pre_build_script runner configuration

.github/workflows/custom_docker_builds.yml
This PR updates our custom docker build action to also build ARM variants of the images. I also bumped the docker actions to the latest versions to ensure they work with these parameters.
=> Build ARM variants of docker images

k8s/staging/sentry/certificates.yaml
I forgot to commit this in #617.
=> Add certificates.yaml for sentry

k8s/production/prometheus/release.yaml
https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L3138
=> Increase prometheus metric retention to 30d

k8s/production/gitlab/release.yaml, k8s/production/karpenter/provisioners/gitlab/provisioner.yaml
Reverts spack/spack-infrastructure#650
=> Revert "Run gitaly by itself on a m5.4xlarge instance (take 2)"

terraform/modules/spack/binary_mirrors.tf
This has been disabled for a while and @scottwittenburg confirmed we don't want this policy anyway.
=> Remove disabled lifecycle policy

k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml
Distinguish pcluster runners with unique tags
CC: @scottwittenburg
=> update tags for pcluster runners

k8s/production/prometheus/custom/runner-pressure.yaml
Update the existing UO cray panel so it shows only Cray RHEL jobs, and add  a new panel that shows only Cray SLES jobs.
=> Update runner pressure db with new cray runner names

k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
- Gitlab chart: 7.6.0
- Runner chart: 0.59.1
=> Upgrade Gitlab to 16.6.0

k8s/production/prometheus/oauth2-proxy.yaml, k8s/staging/prometheus/kustomization.yaml
I changed my github username and thus need to update this list.
=> Update prometheus user

.github/workflows/custom_docker_builds.yml, analytics/Dockerfile, analytics/entrypoint.sh, k8s/production/custom/webhook-handler/deployments.yaml
My only remaining concern is if we should have some check in place to make sure we're not running an old image version? I was thinking of using the migration system to check for that, although I don't know how exactly.
=> Run django migrations before running server

.github/workflows/custom_docker_builds.yml, analytics/analytics/build_timing_processor.py, k8s/production/custom/webhook-handler/deployments.yaml
Follow up to #724
In my efforts to test the change locally I had accidentally changed the access of the job runner id.
=> Fix incorrect indexing of gitlab job runner dict

.github/workflows/custom_docker_builds.yml, images/ci-key-rotate/rotate_gitlab_aws_access_keys.py, k8s/production/custom/rotate-keys/cron-jobs.yaml
Reverts spack/spack-infrastructure#726
=> Revert "Disable gitlab aws access key rotation"

k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/pcluster/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/pcluster/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
=> Fix helper_memory_request units

k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
I applied this to the cluster already and disabled flux until this PR is merged.
=> Upgrade to gitlab 16.9.1, gitlab-runner 16.9.0

k8s/production/ingress-nginx/release.yaml
I applied this to staging and confirmed it works.
=> Upgrade ingress-nginx to 1.10.0

k8s/production/karpenter/provisioners/runners/windows/x86_64/v2/provisioner.yaml, k8s/production/kube-system/enable-windows-ipam.yaml, k8s/staging/karpenter/kustomization.yaml, k8s/staging/kube-system/kustomization.yaml, k8s/staging/runners/protected/windows/x86_64/v2/release.yaml, k8s/staging/runners/public/windows/x86_64/v2/release.yaml, terraform/modules/spack/eks.tf, terraform/modules/spack/karpenter.tf
=> Karpenter windows runners

.github/workflows/custom_docker_builds.yml, k8s/production/custom/webhook-handler/deployments.yaml
=> Bump django image version

k8s/production/prometheus/oauth2-proxy.yaml, k8s/staging/prometheus/kustomization.yaml
=> Add vsoch user to prometheus

scripts/gitlab_runner_pre_build/pre_build.py, scripts/gitlab_runner_pre_build/test_pre_build.py
This should handle the (fairly rare) case of requests timing out e.g. https://gitlab.spack.io/spack/spack/-/jobs/10466875.
=> Add timeout handling to pre_build.py

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
I think `rcp` was meant to be `rpc`
=> Fix typo in classifier name

.github/workflows/custom_docker_builds.yml, images/ci-prune-buildcache/ci_buildcache_prune.py, images/ci-prune-buildcache/entrypoint.sh, k8s/production/custom/prune-buildcache/cron-jobs.yaml
Fixed input argument issue in cron and added some more debug
CC: @danlamanna
=> Pruner debug

k8s/production/prometheus/custom/cost-per-job-dashboard.yaml
This adds a basic Cost per Job dashboard, that can give some numbers on recent jobs. This will be iterated on going forward.
=> Add "Cost Per Job Metrics" dashboard

terraform/modules/spack/eks.tf
Give @cmelone access to the k8s cluster by adding him to the TF configuration.
=> eks.tf: add Caetano to list of allowed users

k8s/production/metabase/metabase-deployment.yaml, k8s/production/prometheus/release.yaml
* Upgrade Metabase to `0.50.5`
* Upgrade kube-prometheus-stack to `60.2.0`
=> Service Upgrade 2024-06-18

k8s/production/prometheus/release.yaml
Documented here:
https://github.com/grafana/helm-charts/tree/main/charts/grafana
=> Use a persistent volume to store data for Grafana

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/prometheus.py, k8s/production/custom/webhook-handler/deployments.yaml
Since the price of a node can change while a job is running, this PR averages the returned node price values from Prometheus.
=> Average node price over job lifetime

k8s/production/gitlab/release.yaml, k8s/production/runners/protected/graviton/2/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/2/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
Upgrade runners to 16.11.3 (latest runner version at the time of this PR)
=> Upgrade Gitlab to 16.11.8

.github/workflows/terraform-drift-detection.yaml
=> Update IAM role name for Terraform drift detection

.github/workflows/custom_docker_builds.yml, analytics/analytics/core/job_failure_classifier/taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
Examples:
https://gitlab.spack.io/spack/spack/-/jobs/13067136 
https://gitlab.spack.io/spack/spack/-/jobs/13067292
=> Add new regex for `concretization_error`

k8s/production/metabase/metabase-deployment.yaml, k8s/production/prometheus/release.yaml
- Upgrade Metabase to `v0.51.3`
- Upgrade kube-prometheus-stack to `v66.2.1`
=> Service Upgrade 2024-11-19

.github/workflows/custom_docker_builds.yml, analytics/analytics/job_processor/error_taxonomy.yaml, k8s/production/custom/webhook-handler/deployments.yaml
See commit descriptions for links to example jobs.
=> Add new `spack_error` regexes

k8s/production/custom/retry-trigger-jobs/cron-jobs.yaml
I tested this by disabling flux and applying the new YAML manually
=> Bug fix to get the new retry-trigger-job cron working

.github/workflows/custom_docker_builds.yml
It seems there is the possibility of a race condition here - https://news.ycombinator.com/item?id=28607735
Thanks @johnwparent !
=> Don't explicitly log out in docker build job

k8s/production/gitlab/release.yaml, k8s/production/prometheus/release.yaml, k8s/production/runners/protected/graviton/3/release.yaml, k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/protected/x86_64/v2/release.yaml, k8s/production/runners/protected/x86_64/v3/release.yaml, k8s/production/runners/protected/x86_64/v4/release.yaml, k8s/production/runners/public/graviton/3/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2/release.yaml, k8s/production/runners/public/x86_64/v3/release.yaml, k8s/production/runners/public/x86_64/v4/release.yaml, k8s/production/runners/signing/release.yaml
* Upgrade gitlab to 17.9.1
* Upgrade gitlab runner to 17.9.1
* Upgrade kube-prometheus-stack to v69.8.2
=> Upgrade Gitlab and Services

k8s/production/runners/protected/x86_64/v2-win/release.yaml, k8s/production/runners/public/x86_64/v2-win/release.yaml
=> Make git auto crlf setting global

k8s/production/metabase/metabase-deployment.yaml, k8s/production/prometheus/release.yaml
- Upgrade metabase to v0.54.1
- Upgrade kube-prometheus-stack to 70.4.2
=> Service Upgrade 2025-04-08

images/notary/sign.sh
Before files had .sig extension, and gpg could guess the operation was verify. The operation had the result of writing the file (minus the clear signature) to disk without the .sig name.
By removing the .sig extension and specifying --verify, the problem was that the signed file was still sitting there (with the signature wrapped around it).  But the signing script then deleted that file in the loop, so there were no files to sign in the next loop.
Now verification puts the extracted files (no more signature) into an intermediate directory, deleting the files in the input directory as it goes.  The next loop iterates files in the intermediate dir, writing the resigned files into the output directory, and deleting the itermediate files in the loop.
=> notary: Fix another issue with changed signing procedure

terraform/modules/spack_gitlab/delete_stale_branches.tf, terraform/modules/spack_gitlab/spack_gantry.tf, terraform/modules/spack_gitlab/spackbot_secrets.tf, terraform/modules/spack_gitlab/webhooks.tf
These were set to expire tomorrow.
=> Bump expiration date for gl tokens

.github/workflows/custom_docker_builds.yml, images/notary/Dockerfile, k8s/production/runners/signing/release.yaml
needed for signing on spack-packages
=> Update notary to include git

k8s/production/custom/retry-trigger-jobs/cron-jobs.yaml
spack-packages is 57, not 52...
=> Fix projectid for retry-trigger-jobs

k8s/production/custom/runner-node-certificate-controller/cron-jobs.yaml
=> Fix indentation error in yaml

.github/workflows/custom_docker_builds.yml, images/gitlab-stuckpods/Dockerfile, k8s/production/custom/gitlab-gitaly-bundle-refresher/cronjobs.yaml, k8s/production/custom/gitlab-restart-webservice/cronjobs.yaml, k8s/production/custom/gitlab-stuckpods/deployment.yaml
See this issue for more details - https://github.com/bitnami/containers/issues/83267
=> Switch to `bitnamisecure` kubectl image

analytics/dev/db-backup-scripts/restore-db.sh
Postgres does not update sequences on `COPY` commands, meaning that our sequences remain at 1 after running `restore-db.sh`.  This PR sets the next sequence to the maximum ID for each table.
=> Update sequences on DB restore
